INSERT INTO faktory_riska_truboprovoda  (
    lineID,
    objID,
    obj_type_faktory_riskaID,
    nalichie_vblizi_kommunikacijID,
    harakter_gruntaID,
    poverhnost_nad_trassojID,
    podtoplenie_do_truby,
    zanos_kanala_gruntomID,
    stroitelnye_konstrukcii_kanalaID,
    sostoyanie_stroitelnyh_konstrukcij_kanalaID,
    vnutrennee_sostoyanie_kanalaID,
    konstrukciya_drenazhnogo_ustrojstvaID,
    sostoyanie_teplovoj_izolyacii_podachaID,
    sostoyanie_teplovoj_izolyacii_obratkaID,
    sostoyanie_naruzhnogo_pokrytiya_podachaID,
    sostoyanie_naruzhnogo_pokrytiya_obratkaID,
    sostoyanie_protivokorrozionnogo_pokrytiya_podachaID,
    sostoyanie_protivokorrozionnogo_pokrytiya_obratkaID,
    Elektrich,
    TransportElekricht,
    Ponezial,
    floodIntensityBWid,
    floodIntensityFWid,
    floodIntensityGWid,
    floodIntensityTWid,
    Vodootved,
    SlozhOkluzh,
    OtkluzhGkal,
    AvariiVipoln,
    Pesehod,
    ZhdDorogi,
    LudiProklad,
    UzherbLudi,
    UzherbSity,
    VnesniiVid,
    SostOborudovania,
    nalichie_korrozii_podachaID,
    nalichie_korrozii_obratkaID,
    VnesnKorrozia,
    VnunrenKorrozia,
    SostKonstrukz,
    zashemID,
    sost_podvID,
    sost_oporID,
    nalich_obrKlID,
    sootv_nadpID,
    nalich_tabl_regID,
    nalich_tabl_parID,
    int_korID,
    sostoyanie_metalla_truboprovodaID,
    tol1,
    tol2,
    glubina_kor,
    razmery_kor,
    document_analiz_vlazhnost,
    document_analiz_korrozia,
    document_potenzial,
    document_analiz_vytyazhka,
    dokument_analiz_prob_na_vlazhnost,
    dokument_analiz_prob_na_korrozijnuyu_aktivnost,
    dokument_raznost_elektricheskih_potencialov,
    dokument_analiz_vodyanoj_vytyazhki,
    dokument_chertezh_objekta_kontrolya,
    diameterCondit,
    diameterExternal,
    diameterInternal,
    wallThickness,
    pipeSectLength,
    isolMaterialID,
    isolationTypeID,
    isolThickness,
    externMaterialID,
    externCoverThick,
    anticorrMaterialID,
    len_tube,
    len_izol,
    asfaltirovanie,
    len_channel,
    zamena_kanala_procent,
    zamena_kompensatorov,
    rekonstrukciya_kamery_nachalnogo_uzla,
    rekonstrukciya_kamery_konechnogo_uzla,
    ustanovka_i_zamena_zadvizhek,
    tubingTypeID
)
select 
lineID,
objID=$objID$,
obj_type_faktory_riskaID=$obj_type_faktory_riskaID$,
MAX(nalichie_vblizi_kommunikacijID) as 'nalichie_vblizi_kommunikacijID',
MAX(harakter_gruntaID) as 'harakter_gruntaID',
MAX(poverhnost_nad_trassojID) as 'poverhnost_nad_trassojID',
MAX(podtoplenie_do_truby) as 'podtoplenie_do_truby',
MAX(zanos_kanala_gruntomID) as 'zanos_kanala_gruntomID',
MAX(stroitelnye_konstrukcii_kanalaID) as 'stroitelnye_konstrukcii_kanalaID',
MAX(sostoyanie_stroitelnyh_konstrukcij_kanalaID) as 'sostoyanie_stroitelnyh_konstrukcij_kanalaID',
MAX(vnutrennee_sostoyanie_kanalaID) as 'vnutrennee_sostoyanie_kanalaID',
MAX(konstrukciya_drenazhnogo_ustrojstvaID) as 'konstrukciya_drenazhnogo_ustrojstvaID',
MAX(sostoyanie_teplovoj_izolyacii_podachaID) as 'sostoyanie_teplovoj_izolyacii_podachaID',
MAX(sostoyanie_teplovoj_izolyacii_obratkaID) as 'sostoyanie_teplovoj_izolyacii_obratkaID',
MAX(sostoyanie_naruzhnogo_pokrytiya_podachaID) as 'sostoyanie_naruzhnogo_pokrytiya_podachaID',
MAX(sostoyanie_naruzhnogo_pokrytiya_obratkaID) as 'sostoyanie_naruzhnogo_pokrytiya_obratkaID',
MAX(sostoyanie_protivokorrozionnogo_pokrytiya_podachaID) as 'sostoyanie_protivokorrozionnogo_pokrytiya_podachaID',
MAX(sostoyanie_protivokorrozionnogo_pokrytiya_obratkaID) as 'sostoyanie_protivokorrozionnogo_pokrytiya_obratkaID',
MAX(Elektrich) as 'Elektrich',
MAX(TransportElekricht) as 'TransportElekricht',
MAX(Ponezial) as 'Ponezial',
MAX(floodIntensityBWid) as 'floodIntensityBWid',
MAX(floodIntensityFWid) as 'floodIntensityFWid',
MAX(floodIntensityGWid) as 'floodIntensityGWid',
MAX(floodIntensityTWid) as 'floodIntensityTWid',
MAX(Vodootved) as 'Vodootved',
MAX(SlozhOkluzh) as 'SlozhOkluzh',
MAX(OtkluzhGkal) as 'OtkluzhGkal',
MAX(AvariiVipoln) as 'AvariiVipoln',
MAX(Pesehod) as 'Pesehod',
MAX(ZhdDorogi) as 'ZhdDorogi',
MAX(LudiProklad) as 'LudiProklad',
MAX(UzherbLudi) as 'UzherbLudi',
MAX(UzherbSity) as 'UzherbSity',
MAX(VnesniiVid) as 'VnesniiVid',
MAX(SostOborudovania) as 'SostOborudovania',
MAX(nalichie_korrozii_podachaID) as 'nalichie_korrozii_podachaID',
MAX(nalichie_korrozii_obratkaID) as 'nalichie_korrozii_obratkaID',
MAX(VnesnKorrozia) as 'VnesnKorrozia',
MAX(VnunrenKorrozia) as 'VnunrenKorrozia',
MAX(SostKonstrukz) as 'SostKonstrukz',
MAX(zashemID) as 'zashemID',
MAX(sost_podvID) as 'sost_podvID',
MAX(sost_oporID) as 'sost_oporID',
MAX(nalich_obrKlID) as 'nalich_obrKlID',
MAX(sootv_nadpID) as 'sootv_nadpID',
MAX(nalich_tabl_regID) as 'nalich_tabl_regID',
MAX(nalich_tabl_parID) as 'nalich_tabl_parID',
MAX(int_korID) as 'int_korID',
MAX(sostoyanie_metalla_truboprovodaID) as 'sostoyanie_metalla_truboprovodaID',
MAX(tol1) as 'tol1',
MAX(tol2) as 'tol2',
MAX(glubina_kor) as 'glubina_kor',
MAX(razmery_kor) as 'razmery_kor',
MAX(document_analiz_vlazhnost) as 'document_analiz_vlazhnost',
MAX(document_analiz_korrozia) as 'document_analiz_korrozia',
MAX(document_potenzial) as 'document_potenzial',
MAX(document_analiz_vytyazhka) as 'document_analiz_vytyazhka',
MAX(dokument_analiz_prob_na_vlazhnost) as 'dokument_analiz_prob_na_vlazhnost',
MAX(dokument_analiz_prob_na_korrozijnuyu_aktivnost) as 'dokument_analiz_prob_na_korrozijnuyu_aktivnost',
MAX(dokument_raznost_elektricheskih_potencialov) as 'dokument_raznost_elektricheskih_potencialov',
MAX(dokument_analiz_vodyanoj_vytyazhki) as 'dokument_analiz_vodyanoj_vytyazhki',
MAX(dokument_chertezh_objekta_kontrolya) as 'dokument_chertezh_objekta_kontrolya',
MAX(diameterCondit) as 'diameterCondit',
MAX(diameterExternal) as 'diameterExternal',
MAX(diameterInternal) as 'diameterInternal',
MAX(wallThickness) as 'wallThickness',
MAX(pipeSectLength) as 'pipeSectLength',
MAX(isolMaterialID) as 'isolMaterialID',
MAX(isolationTypeID) as 'isolationTypeID',
MAX(isolThickness) as 'isolThickness',
MAX(externMaterialID) as 'externMaterialID',
MAX(externCoverThick) as 'externCoverThick',
MAX(anticorrMaterialID) as 'anticorrMaterialID',
MAX(len_tube) as 'len_tube',
MAX(len_izol) as 'len_izol',
MAX(asfaltirovanie) as 'asfaltirovanie',
MAX(len_channel) as 'len_channel',
MAX(zamena_kanala_procent) as 'zamena_kanala_procent',
MAX(zamena_kompensatorov) as 'zamena_kompensatorov',
MAX(convert(int,rekonstrukciya_kamery_nachalnogo_uzla)) as 'rekonstrukciya_kamery_nachalnogo_uzla',
MAX(convert(int,rekonstrukciya_kamery_konechnogo_uzla)) as 'rekonstrukciya_kamery_konechnogo_uzla',
MAX(ustanovka_i_zamena_zadvizhek) as 'ustanovka_i_zamena_zadvizhek',
MAX(tubingTypeID) as 'tubingTypeID'
from (
	select 
        r.id as r_id,
        fr.*,
		r.typ,
		r.dt as max_cur,
		MAX(r.dt) over (partition by fr.lineID, r.typ)  as max_all,
        MAX(fr.id) over (PARTITION by fr.lineID, r.typ) as max_row
	from faktory_riska_truboprovoda fr
	left join (SELECT id, 3 AS typ,
    CASE
    WHEN s.data_zaversheniya_remonta IS NOT NULL THEN s.data_zaversheniya_remonta
    WHEN s.data_nachala_remonta IS NOT NULL THEN s.data_nachala_remonta
    WHEN s.data_okonchaniya_plan IS NOT NULL THEN s.data_okonchaniya_plan
    WHEN s.data_nachala_plan IS NOT NULL THEN s.data_nachala_plan
    END AS dt
    FROM remont2 s
    UNION

    SELECT id, 2 AS typ,
    CASE
    WHEN s.data_osmotra IS NOT NULL THEN s.data_osmotra
    END as dt
    FROM osmotr s
    UNION

    SELECT id, 1 AS typ, 
    CASE 
    WHEN s.data_okonchaniya IS NOT NULL THEN s.data_okonchaniya
    WHEN s.data_nachala IS NOT NULL THEN s.data_nachala
    WHEN s.data_okonchaniya_plan IS NOT NULL THEN s.data_okonchaniya_plan
    WHEN s.data_nachala_plan IS NOT NULL THEN s.data_nachala_plan
    END as dt
    FROM shurfy s ) r ON r.id = fr.objID
	where fr.lineID IN ($lineID$)
)t
where max_cur = max_all and id = max_row
GROUP by lineID

