UPDATE pss
  set
    tubingTypeID = f.tubingTypeID,
    len_tube = f.len_tube,
    diameterCondit = f.diameterCondit,
    diameterExternal = f.diameterExternal,
    diameterInternal = f.diameterInternal,
    wallThickness = f.wallThickness,
    len_channel = f.len_channel,
    len_izol = f.len_izol,
    isolMaterialID = f.isolMaterialID,
    isolationTypeID = f.isolationTypeID,
    isolThickness = f.isolThickness,
    externMaterialID = f.externMaterialID,
    externCoverThick = f.externCoverThick,
    anticorrMaterialID = f.anticorrMaterialID,
    asfaltirovanie = f.asfaltirovanie,
    Elektrich = f.Elektrich,
    TransportElekricht = f.TransportElekricht,
    Pesehod = f.Pesehod,
    ZhdDorogi = f.ZhdDorogi,
    LudiProklad = f.LudiProklad,
    harakter_gruntaID = f.harakter_gruntaID,
    podtoplenie_do_truby = f.podtoplenie_do_truby,
    zanos_kanala_gruntomID = f.zanos_kanala_gruntomID,
    SostKonstrukz = f.SostKonstrukz,
    sostoyanie_stroitelnyh_konstrukcij_kanalaID = f.sostoyanie_stroitelnyh_konstrukcij_kanalaID,
    vnutrennee_sostoyanie_kanalaID = f.vnutrennee_sostoyanie_kanalaID,
    konstrukciya_drenazhnogo_ustrojstvaID = f.konstrukciya_drenazhnogo_ustrojstvaID,
    Vodootved = f.Vodootved,
    VnesniiVid = f.VnesniiVid,
    SostOborudovania = f.SostOborudovania,
    nalichie_korrozii_podachaID = f.nalichie_korrozii_podachaID,
    nalichie_korrozii_obratkaID = f.nalichie_korrozii_obratkaID,
    sostoyanie_metalla_truboprovodaID = f.sostoyanie_metalla_truboprovodaID,
    sostoyanie_teplovoj_izolyacii_podachaID = f.sostoyanie_teplovoj_izolyacii_podachaID,
    sostoyanie_teplovoj_izolyacii_obratkaID = f.sostoyanie_teplovoj_izolyacii_obratkaID,
    sostoyanie_naruzhnogo_pokrytiya_podachaID = f.sostoyanie_naruzhnogo_pokrytiya_podachaID,
    sostoyanie_naruzhnogo_pokrytiya_obratkaID = f.sostoyanie_naruzhnogo_pokrytiya_obratkaID,
    sostoyanie_protivokorrozionnogo_pokrytiya_podachaID = f.sostoyanie_protivokorrozionnogo_pokrytiya_podachaID,
    sostoyanie_protivokorrozionnogo_pokrytiya_obratkaID = f.sostoyanie_protivokorrozionnogo_pokrytiya_obratkaID,
    zamena_kanala_procent = f.zamena_kanala_procent,
    zamena_kompensatorov = f.zamena_kompensatorov,
    rekonstrukciya_kamery_nachalnogo_uzla = f.rekonstrukciya_kamery_nachalnogo_uzla,
    rekonstrukciya_kamery_konechnogo_uzla = f.rekonstrukciya_kamery_konechnogo_uzla,
    ustanovka_i_zamena_zadvizhek = f.ustanovka_i_zamena_zadvizhek

from pipeSections pss
join faktory_riska_truboprovoda f ON f.lineID = pss.id AND f.id = $faktorID$ AND f.obj_type_faktory_riskaID = 3


