UPDATE pss
    set nalichie_vblizi_kommunikacijID = f.nalichie_vblizi_kommunikacijID





from pipeSections pss
join (
    select 
    id,
    lineID,
    nalichie_vblizi_kommunikacijID,
    harakter_gruntaID,
    poverhnost_nad_trassojID,
    podtoplenie_do_truby,
    zanos_kanala_gruntomID,
    stroitelnye_konstrukcii_kanalaID,
    sostoyanie_stroitelnyh_konstrukcij_kanalaID,
    vnutrennee_sostoyanie_kanalaID,
    konstrukciya_drenazhnogo_ustrojstvaID,
    sostoyanie_teplovoj_izolyacii_podachaID,
    sostoyanie_teplovoj_izolyacii_obratkaID,
    sostoyanie_naruzhnogo_pokrytiya_podachaID,
    sostoyanie_naruzhnogo_pokrytiya_obratkaID,
    sostoyanie_protivokorrozionnogo_pokrytiya_podachaID,
    sostoyanie_protivokorrozionnogo_pokrytiya_obratkaID,
    Elektrich,
    TransportElekricht,
    Ponezial,
    floodIntensityBWid,
    floodIntensityFWid,
    floodIntensityGWid,
    floodIntensityTWid,
    Vodootved,
    SlozhOkluzh,
    OtkluzhGkal,
    AvariiVipoln,
    Pesehod,
    ZhdDorogi,
    LudiProklad,
    UzherbLudi,
    UzherbSity,
    VnesniiVid,
    SostOborudovania,
    nalichie_korrozii_podachaID,
    nalichie_korrozii_obratkaID,
    VnesnKorrozia,
    VnunrenKorrozia,
    SostKonstrukz,
    zashemID,
    sost_podvID,
    sost_oporID,
    nalich_obrKlID,
    sootv_nadpID,
    nalich_tabl_regID,
    nalich_tabl_parID,
    int_korID,
    sostoyanie_metalla_truboprovodaID,
    tol1,
    tol2,
    glubina_kor,
    razmery_kor,
    document_analiz_vlazhnost,
    document_analiz_korrozia,
    document_potenzial,
    document_analiz_vytyazhka,
    dokument_analiz_prob_na_vlazhnost,
    dokument_analiz_prob_na_korrozijnuyu_aktivnost,
    dokument_raznost_elektricheskih_potencialov,
    dokument_analiz_vodyanoj_vytyazhki,
    dokument_chertezh_objekta_kontrolya,
    diameterCondit,
    diameterExternal,
    diameterInternal,
    wallThickness,
    pipeSectLength,
    isolMaterialID,
    isolationTypeID,
    isolThickness,
    externMaterialID,
    externCoverThick,
    anticorrMaterialID,
    len_tube,
    len_izol,
    asfaltirovanie,
    len_channel,
    zamena_kanala_procent,
    zamena_kompensatorov,
    rekonstrukciya_kamery_nachalnogo_uzla,
    rekonstrukciya_kamery_konechnogo_uzla,
    ustanovka_i_zamena_zadvizhek,
    tubingTypeID
    from faktory_riska_truboprovoda fr
) f on f.lineID = $lineID$