move defect-00.png RemontPovrDefAdd.png
move defect-01.png RemontPovrDefDel.png
move defect-02.png RemontPovrDefMove.png
move defect-03.png RemontPovrDefInfo.png
move defect-04.png DefectZhurnalExpluatacia.png
move defect-05.png DefectZhurnalShurf.png
move defect-06.png DefectZhurnalOsmotr.png
move defect-07.png DefectZhurnalOpress.png
move defect-08.png DefectZhurnalNarushenie.png
move defect-09.png DefectZhurnalRemont.png
move defect-10.png DefectZhurnalPosleRemont.png
move defect-11.png DefectZhurnalAll.png
move defect-12.png DefectWord1.png
move defect-13.png DefectWord2.png
move defect-14.png DefectDocTable.png
move defect-15.png DefectAnaliz.png
move defect-16.png RemontPovrDefOtobr.png
move defect-17.png RemontPovrOtop.png
move defect-18.png RemontOsmotrTeploSet.png

move shurfy-00.png  RemontPovrShurfAdd.png
move shurfy-01.png  RemontPovrShurfAddNeplan.png
move shurfy-02.png  RemontPovrShurfDel.png
move shurfy-03.png  RemontPovrShurfMove.png
move shurfy-04.png  RemontPovrShurfInfo.png
move shurfy-05.png  RemontShurfPlan.png
move shurfy-06.png  RemontShurfPredpis.png
move shurfy-07.png  RemontShurfNarush.png
move shurfy-08.png  ShurfProcess.png
move shurfy-09.png  ShurfVypolneno.png
move shurfy-10.png  ShurfAll.png
move shurfy-11.png  RemontShurfPlanUtverdit.png
move shurfy-12.png  RemontShurfPlanExcel.png
move shurfy-13.png  RemontShurfPlanExcelMonth.png
move shurfy-14.png  ShurfTable.png
move shurfy-15.png  RemontShurfOtobr.png
move shurfy-16.png  RemontPovrOtop.png
move shurfy-17.png  RemontOsmotrTeploSet.png
move shurfy-18.png  ShurfBezUch.png

move osmotr-00.png OsmotrAdd.png
move osmotr-01.png OsmotrSave.png
move osmotr-02.png ListOsmotr2.png
move osmotr-03.png LastOsmotr2.png
move osmotr-04.png LastFaktory.png
move osmotr-05.png OsmotrZapros1.png
move osmotr-06.png OsmotrZapros2.png
move osmotr-07.png OsmotrZapros3.png
move osmotr-08.png OsmotrAnaliz2.png     
move osmotr-09.png OsmotrAnaliz.png          
move osmotr-10.png RemontPovrDefOtobr.png    
move osmotr-11.png RemontPovrOtop.png            
move osmotr-12.png RemontOsmotrTeploSet.png  
move osmotr-13.png MarkRev.png

move remont-00.png  RemontAddPlan.png
move remont-01.png  RemontAddCurrent.png
move remont-02.png  RemontSave.png
move remont-03.png  ListRemont2.png
move remont-04.png  LastRemont2.png
move remont-05.png  RemontTrub.png
move remont-06.png  RemontPlan.png
move remont-07.png  RemontCurrent.png
move remont-08.png  RemontProcess.png
move remont-09.png  RemontVypolneno.png
move remont-10.png  RemontAll2.png
move remont-11.png  RemontWord1.png
move remont-12.png  RemontWord2.png
move remont-13.png  RemontWord3.png
move remont-14.png  RemontAnaliz2.png
move remont-15.png  RemontAnaliz.png
move remont-16.png  RemontPovrDefOtobr.png
move remont-17.png  RemontPovrOtop.png
move remont-18.png  RemontOsmotrTeploSet.png
move remont-19.png  RemontVyborNach.png
move remont-20.png  MarkRev.png

move opres-00.png OpresAddPlan.png
move opres-01.png OpresSave.png
move opres-02.png OpresGranitsaRazdela.png
move opres-03.png ListOpres.png
move opres-04.png LastOpres.png
move opres-05.png OpresPlan.png
move opres-06.png OpresProcess.png
move opres-07.png OpresVypolneno.png
move opres-08.png OpresAll2.png
move opres-09.png OpresWord1.png
move opres-10.png OpresWord2.png
move opres-11.png OpresAnaliz2.png
move opres-12.png OpresAnaliz.png
move opres-13.png RemontPovrDefOtobr.png
move opres-14.png RemontPovrOtop.png
move opres-15.png RemontOsmotrTeploSet.png
move opres-16.png OpresVyborNach.png
move opres-17.png ListRemont2.png
move opres-18.png MarkRev.png


