class QAction;
class QShortcut;

struct GidrAction
{
QAction *aFileClose = nullptr; // Закрыть
QAction *aEditor1 = nullptr; // Режимы
QAction *aEditor2 = nullptr; // Просмотр схемы
QAction *aEditor4 = nullptr; // АРМ
QAction *aSqlSave = nullptr; // Создание копии Базы данных
QAction *aSqlCopyFragment = nullptr; // Вставить Фрагмент схемы
QAction *aSqlDelFragment = nullptr; // Удалить Фрагмент схемы

QAction *aAddFragment = nullptr; // Добавить Фрагмент схемы
QAction *aExportFragment = nullptr; // Экспорт фрагмента
QAction *aExportFragmentVyd = nullptr; // Экспорт выделенного фрагмента
QAction *aExportFragmentsMulty = nullptr; // Экспорт всех фрагментов
QAction *aImportFragment = nullptr; // Импорт фрагмента
QAction *aImportFragmentMdb = nullptr; // Конвертор ТГИД-05/ ТГИД-07
QAction *aMainCxema = nullptr; // Активная схема
QAction *aAddDop = nullptr; // Отобразить дополнительную схему
QAction *aBmp = nullptr; // Файл графической подложки...
QAction *aBmpFind = nullptr; // Найти графическую подложку
QAction *aCatalog = nullptr; // Каталоги
QAction *aFilePrint = nullptr; // Печать...\tCtrl+P
QAction *aFilePrintPreview = nullptr; // Предварительный просмотр
QAction *aPrintFr = nullptr; // Фрагмент для печати
QAction *aFragment = nullptr; // Выделить фрагмент
QAction *aBdDel = nullptr; // Удалить базу


QAction *aFilePrintSetup = nullptr; // Параметры страницы...


QAction *aAppExit = nullptr; // Выход
QAction *aEditFindNode = nullptr; // Найти узел...\tCtrl+F
QAction *aEditUndo = nullptr; // Отменить\tCtrl+Z
QAction *aEditUndoTU = nullptr; // Отменить\tCtrl+Z
QAction *aResetGid = nullptr; // 
QAction *aToGid9 = nullptr; // 

QAction *aEditUndoDel = nullptr; // Отменить удаления
QAction *aZapVnCx = nullptr; // Узлы с внутренней схемой
QAction *aZapNullGeo = nullptr; // Узлы с нулевой геодезической отметкой
QAction *aOdnolin = nullptr; // Однолинейные участки
QAction *aRaznolin = nullptr; // Участки с разными подачей и обраткой
QAction *aRasprMag = nullptr; // Расчетные схемы
QAction *aRasprMag2 = nullptr; // Объекты системы теплоснабжения
QAction *aIstSetyNew = nullptr; // Источник новый
QAction *aIstSety = nullptr; // Источник
QAction *aVyd = nullptr; // Фрагмент сети
QAction *aBalans = nullptr; // Балансовая принадлежность
QAction *aTubing1 = nullptr; // Канальная
QAction *aTubing2 = nullptr; // Бесканальная
QAction *aTubing4 = nullptr; // Надземная
QAction *aTubing3 = nullptr; // Подвальная
QAction *aTubing5 = nullptr; // Обвязка узлов и насосных станций
QAction *aFindKti = nullptr; // По коэффициенту тепловых испытаний
QAction *aMark = nullptr; // Выделить область
QAction *aSetOtv = nullptr; // Установить ФИО техников
QAction *aSetTr = nullptr; // Установить Код расчетных температур
QAction *aSetUr = nullptr; // Установить Код удельных расходов
QAction *aSetKvPt = nullptr; // Установить Коэффициенты вариации по потребителям
QAction *aSetUf = nullptr; // Установить Коэффициенты смешения элеватора
QAction *aSetTp = nullptr; // Установить Тепловые пункты по потребителям
QAction *aSetUdobVent = nullptr; // Установить Удельный объем системы вентиляции
QAction *aSetUdobOt = nullptr; // Установить Удельный объем системы отопления
QAction *aSetOpenKoef = nullptr; // Коэф. часовой неравномерности
QAction *aSetOpenRez = nullptr; // Расчетные тепловые потери в рециркуляц. контуре ГВС
QAction *aSetOpenRezT = nullptr; // Температура в рециркуляционном трубопроводе ГВС
QAction *aSetOpenGvsT = nullptr; // Расчетная температура горячей воды
QAction *aSetDiams = nullptr; // Установить Диаметр
QAction *aSetLosesShare = nullptr; // Установить Долю местных потерь
QAction *aSetKolChas = nullptr; // Установить Количество часов работы
QAction *aSetKvUt = nullptr; // Установить Коэффициенты вариации по участкам
QAction *aSetKti = nullptr; // Установить Коэффициенты тепловых испытаний
QAction *aSetOrg = nullptr; // Установить Организации
QAction *aSetPipeRemontType = nullptr; // Установить Признак ремонта
QAction *aSetTubingType = nullptr; // Установить Тип прокладки
QAction *aSetSher = nullptr; // Установить Эквивалентную шероховатость
QAction *aSetDate2 = nullptr; // Установить Дату первичного ввода в эксплуатацию
QAction *aSetDate1 = nullptr; // Установить Дату последней перекладки
QAction *aSetDate3 = nullptr; // Установить Дату планируемого ремонта
QAction *aSetKodRs = nullptr; // Установить Код расчетной схемы
QAction *aGeodz = nullptr; // Установить Отметки узлов горизонтали
QAction *aSetKorrozia = nullptr; // Установить Индикаторы коррозии
QAction *aSetPodpOn = nullptr; // Показать Надписи
QAction *aSetPodpOff = nullptr; // Не отображать Надписи
QAction *aFragmentPoly = nullptr; // Выделить многоугольный фрагмент
QAction *aMoveVyd = nullptr; // Передвинуть фрагмент
//QAction *aFragment = nullptr; // Выделить фрагмент
QAction *aEditCopy = nullptr; // Копировать\tCtrl+C
QAction *aEditCopyPng = nullptr; // Копировать в PNG
QAction *aViewToolbarMain = nullptr; // Главная
QAction *aViewToolbarCxema = nullptr; // Схема
QAction *aViewToolbarZ = nullptr; // Запросы
QAction *aViewToolbar2PtsNew = nullptr; // Паспортизация
QAction *aTuOnOff = nullptr; // Технические условия
QAction *aViewToolbarElectro = nullptr; // Электрические сети
QAction *aViewToolbarControlTu = nullptr; // Контроль технического состояния
//QAction *aViewToolbar2Remont = nullptr; // Ремонт
//QAction *aViewToolbarOpressovka = nullptr; // Опрессовки
QAction *aViewToolbarKorrozia = nullptr; // Индикаторы коррозии
QAction *aNavigator = nullptr; // Навигатор
QAction *aLeftBar = nullptr; // Проводник карты
QAction *aMagAlma = nullptr; // Проводник структуры сети
QAction *aBottomRemont = nullptr; // Проводник мониторинга
QAction *aProtocol = nullptr; // Протокол
QAction *aMovew = nullptr; // Перемещение\tM
QAction *aPovorot = nullptr; // Повернуть
QAction *aPovorot2 = nullptr; // Возврат
QAction *aMasall = nullptr; // Отобразить всю схему\tF3
QAction *aPlus = nullptr; // Увеличить\t+
QAction *aMinus = nullptr; // Уменьшить\t-
QAction *aMasshtab = nullptr; // Масштаб...\tCtrl+F3
QAction *aZoom = nullptr; // Масштабировать
QAction *aPicture = nullptr; // Графическая подложка
QAction *aF5 = nullptr; // Перерисовать схему\tF5
QAction *aCtrlF5 = nullptr; // Перерисовать схему\tF5
QAction *aGeobaza = nullptr; // Показать геобазу
QAction *aFindGeo = nullptr; // Поиск в геобазе...
QAction *aGeoFindNext = nullptr; // Продолжение поиска
QAction *aFindGeoAddr = nullptr; // Поиск по адресу
QAction *aGeoInfo = nullptr; // Информация из геобазы
QAction *aSetLength = nullptr; // Установить длины
QAction *a1000 = nullptr; // Создать файл полей
QAction *a1001 = nullptr; // Переименовать поля
QAction *a1002 = nullptr; // Сохранить переименованные поля
QAction *aNode = nullptr; // Установить узел\tN
QAction *aLine = nullptr; // Линейный объект\tL
QAction *aRename = nullptr; // Изменить тип объекта
QAction *aZn = nullptr; // Узел с заданным напором
QAction *aKam = nullptr; // Внутренняя схема
QAction *aKamVnesh = nullptr; // Внутренняя схема

QAction *aNodeNeotr = nullptr; // Установка конвертированных узлов\tC
QAction *aZapNezak = nullptr; // Незаконченные узлы
QAction *aSetCoordNull = nullptr; // Удалить координаты выделенных узлов
QAction *aNodeMove = nullptr; // Перенести\tV
QAction *aDel = nullptr; // Удалить объект\tD
QAction *aOpenClose = nullptr; // Закрыть/открыть объект
QAction *aNodeMove1 = nullptr; // Разъединить линии
QAction *aSwap = nullptr; // Изменить направление потока
QAction *aMoveLineEnd = nullptr; // Перенести линию
QAction *aMoveLineEndNext = nullptr; // Перенести линию продолжение
QAction *aText = nullptr; // Установить текст
QAction *aDoItDr = nullptr; // Плановый...
QAction *aDoIt = nullptr; // Фактический...
QAction *aDoItListDr = nullptr; // Плановый по списку...
QAction *aDoItList = nullptr; // Фактический по списку...
QAction *aMagFragment = nullptr; // Магистральный фрагмент
QAction *aNapr = nullptr; // Выбpать напpавление
QAction *aSavePjezo = nullptr; // Сохранить направление...
QAction *aListPjezo = nullptr; // Список направлений...
QAction *aClearOut = nullptr; // Удалить старые расчеты
//QAction *aProtocol = nullptr; // Протокол
QAction *aInfo = nullptr; // Свойства объекта\tI
QAction *aViewDb = nullptr; // Таблицы...
QAction *aNovisual = nullptr; // Системные параметры...
QAction *aMoveTo = nullptr; // Таблица объекта
QAction *aInfoGid = nullptr; // Результат расчета
QAction *aOut2 = nullptr; // Отчеты...
QAction *aTableDan = nullptr; // Редактор таблиц...
QAction *aExcel2 = nullptr; // Таблицы Excel...
QAction *aInf = nullptr; // Отображаемая информация...
QAction *aGidinf = nullptr; // Отображать информацию
QAction *aPodp = nullptr; // Отображать имена узлов
QAction *aPodpAll = nullptr;
QAction *aPodpPo = nullptr; // Отоброжать схему ПТС
QAction *aPodpRes = nullptr; // Отображать имена узлов с #
QAction *aPribor = nullptr; // Отображать Приборы учета
QAction *aRezhim = nullptr; // Отображать вспомогательные участки
QAction *aPopupPodpOn = nullptr; // Показать скрытые имена
QAction *aPopupPodpOff = nullptr; // Не показывать скрытые имена
QAction *aPodpYesNo = nullptr; // Отображать/Не отображать надпись
QAction *aNaprGid = nullptr; // Распределение потоков
QAction *aF4 = nullptr; // Измерить расстояние\tF4
QAction *aAnal = nullptr; // Анализ...
QAction *aAdmissibilityAnalysis = nullptr; // Анализ допустимости
QAction *aZaprosy = nullptr; // Запросы
QAction *aZaprosy2 = nullptr; // Запросы2
QAction *aRunProgram = nullptr; //

QAction *aAnalVyd = nullptr; // Анализ выделение
QAction *aColorLine = nullptr; // Участки
QAction *aColorLine1 = nullptr; // Потребители
QAction *aZap1 = nullptr; // Объем сети
QAction *aZap2 = nullptr; // Длина теплопроводов
QAction *aZap7 = nullptr; // Длина теплопроводов по диаметрам
QAction *aZap71 = nullptr; // Длина теплопроводов по диаметрам и способам прокладки
QAction *aTimePr = nullptr; // Время прохождения
QAction *aPoteri = nullptr; // Тепловые потери
QAction *aZap3 = nullptr; // Теплопотребление полученное
QAction *aZap4 = nullptr; // Теплопотребление в закрытых системах полученное
QAction *aZap5 = nullptr; // Теплопотребление в открытых системах полученное
QAction *aZap6 = nullptr; // Закрытые потребители
QAction *aPotNagr0 = nullptr; // С нулевой нагрузкой
QAction *aPotrOtkl = nullptr; // Отключенные потребители
QAction *aUtZakr = nullptr; // Закрытые участки
QAction *aUtZakrAll = nullptr; // Отключенные участки
QAction *aZapOtr = nullptr; // Отрицательные перепады
QAction *aPtTempMin = nullptr; // Низкие температуры
QAction *aZavozd = nullptr; // Завоздушивание
QAction *aIsprLast = nullptr; // Изменённые объекты
QAction *aPjezo = nullptr; // Пьезометр
QAction *aZona = nullptr; // Гидростатические зоны
//QAction *aTuOnOff = nullptr; // Объекты ТУ
QAction *aNagrZd = nullptr; // Физические лица
QAction *aNagrOrg = nullptr; // Юридические лица
QAction *aTuTable = nullptr; // Технические условия
QAction *aTuYear = nullptr; // ТУ по годам
QAction *aTuSost = nullptr; // ТУ состояние
QAction *aTuExcel = nullptr; // Итоговый тепловой баланс
QAction *aTuSvod = nullptr; // Итоговые по годам
QAction *aTuZhurnal = nullptr; // Журнал регистрации ТУ
QAction *aFindTuIst = nullptr; // ТУ по источнику
QAction *aTuFind = nullptr; // ТУ, Договора
QAction *aPrisNagrEdit = nullptr; // Присоединенная нагрузка по источникам
QAction *aQGvs = nullptr; // Коэффициент перевода k=Qгвmax/Qгвср
QAction *aNagrZdNeiz = nullptr; // Физические лица
QAction *aNagrOrgNeiz = nullptr; // Юридические лица
QAction *aTuTableNeiz = nullptr; // Ненайденные ТУ на карте
QAction *aTuIst = nullptr; // Отчет по источникам
//QAction *aViewToolbar2PtsNew = nullptr; // Панель Объекты ПТС
QAction *aPtsAdd = nullptr; // Установить объект
QAction *aPtsInfo = nullptr; // Информация по объекту
QAction *aPtsTable = nullptr; // Таблица
QAction *aPtsDel = nullptr; // Удалить объект
QAction *aProtPass = nullptr; // Протяженность
QAction *aProtNew = nullptr; // Протяженность выделенных трубопроводов
QAction *aProtMag = nullptr; // Протяженность магистралей
QAction *aProtRs = nullptr; // Протяженность распредсетей
QAction *aProtKot = nullptr; // Протяженность котельных
QAction *aPaspNew = nullptr; // Паспорт сети


//--- Ремонты

QAction *aToolbarRemont2Defect = nullptr; // Панель Нарушений
QAction *aToolbarRemont2Shurf = nullptr; // Панель Шурфовки
QAction *aToolbarRemont2Osmotr = nullptr; // Панель Осмотра
QAction *aToolbarRemont2Remont = nullptr; // Панель Ремонтов
QAction *aToolbarRemont2Opres = nullptr; // Панель Опрессовки
QAction *aRemontPovrDefAdd = nullptr; // Установить нарушение
QAction *aRemontPovrDefDel = nullptr; // Удалить нарушение
QAction *aRemontPovrDefMove = nullptr; // Перенести нарушение
QAction *aRemontPovrDefInfo = nullptr; // Свойства объекта Нарушение
QAction *aDefectZhurnalExpluatacia = nullptr; // Нарушения эксплуатации
QAction *aDefectZhurnalShurf = nullptr; // Нарушения в шурфе
QAction *aDefectZhurnalOsmotr = nullptr; // Нарушения осмотра
QAction *aDefectZhurnalOpress = nullptr; // Нарушения опрессовки
QAction *aDefectZhurnalNarushenie = nullptr; // Нарушения до ремонта
QAction *aDefectZhurnalRemont = nullptr; // Нарушения в процессе ремонта
QAction *aDefectZhurnalPosleRemont = nullptr; // Нарушения после ремонта
QAction *aDefectZhurnalAll = nullptr; // Отобразить все нарушения
QAction *aDefectWord1 = nullptr; // Журнал нарушений
QAction *aDefectWord2 = nullptr; // Нарушения/ремонты трубопроводов тепловой сети(документ)
QAction *aDefectDocTable = nullptr; // Нарушения/ремонты трубопроводов тепловой сети
QAction *aDefectAnaliz = nullptr; // Анализ нарушений
QAction *aRemontPovrDefOtobr = nullptr; // Включить/отключить отображение объектов
QAction *aRemontPovrOtop = nullptr; // Выбор отопительного сезона
QAction *aRemontOsmotrTeploSet = nullptr; // Выбор фрагмента сети по Начальнику участка
QAction *aDefectBezUch = nullptr; // Нарушения без участков
QAction *aRemontPovrShurfAdd = nullptr; // Установить плановый шурф
QAction *aRemontPovrShurfAddNeplan = nullptr; // Установить НЕплановый шурф
QAction *aRemontPovrShurfDel = nullptr; // Удалить шурф
QAction *aRemontPovrShurfMove = nullptr; // Перенести шурф
QAction *aRemontPovrShurfInfo = nullptr; // Свойства объекта Шурф
QAction *aRemontShurfPlan = nullptr; // Плановые шурфы
QAction *aRemontShurfPredpis = nullptr; // Шурфы предписания
QAction *aRemontShurfNarush = nullptr; // Шурфы нарушения
QAction *aShurfProcess = nullptr; // Шурфы в процессе выполнения
QAction *aShurfVypolneno = nullptr; // Шурфы выполненные
QAction *aShurfAll = nullptr; // Отобразить все Шурфы
QAction *aRemontShurfPlanUtverdit = nullptr; // Утвердить План шурфов Отопительного сезона
QAction *aRemontShurfPlanExcel = nullptr; // План шурфов (документ)
QAction *aRemontShurfPlanExcelMonth = nullptr; // План шурфов по месяцам (документ)
QAction *aShurfTable = nullptr; // Анализ Плана шурфов
QAction *aRemontShurfOtobr = nullptr; // Включить/отключить отображение объектов
//QAction *aRemontPovrOtop = nullptr; // Выбор отопительного сезона
//QAction *aRemontOsmotrTeploSet = nullptr; // Выбор фрагмента сети по Начальнику участка
QAction *aShurfBezUch = nullptr; // Шурфовки без участков
QAction *aOsmotrAdd = nullptr; // Создать контур осмотра
QAction *aOsmotrSave = nullptr; // Обновить сохранение контура
QAction *aListOsmotr2 = nullptr; // Выполнить осмотр контура
QAction *aLastOsmotr2 = nullptr; // Последний контур осмотра
QAction *aLastFaktory = nullptr; // Выбор трубопроводов для осмотра
QAction *aOsmotrZapros1 = nullptr; // Осмотренные фрагменты сети
QAction *aOsmotrZapros2 = nullptr; // Осмотренные трубопроводы за период
QAction *aOsmotrZapros3 = nullptr; // Неосмотренные трубопроводы за период
QAction *aOsmotrAnaliz2 = nullptr; // Анализ осмотра контуров
QAction *aOsmotrAnaliz = nullptr; // Анализ осмотра трубопроводов контура
//QAction *aRemontPovrDefOtobr = nullptr; // Включить/отключить отображение объектов
//QAction *aRemontPovrOtop = nullptr; // Выбор отопительного сезона
//QAction *aRemontOsmotrTeploSet = nullptr; // Выбор фрагмента сети по Начальнику участка
QAction *aRemontAddPlan = nullptr; // Сохранить контур плана ремонта
QAction *aRemontAddCurrent = nullptr; // Сохранить контур текущего ремонта
QAction *aRemontSave = nullptr; // Обновить сохранение контура
QAction *aListRemont2 = nullptr; // Список контуров ремонтов
QAction *aLastRemont2 = nullptr; // Последний контур ремонта
QAction *aRemontTrub = nullptr; // Выбор трубопроводов контура ремонта
QAction *aRemontPlan = nullptr; // Контуры капитального/инвестиционного ремонтов
QAction *aRemontCurrent = nullptr; // Контуры текущих ремонтов
QAction *aRemontProcess = nullptr; // Ремонт в процессе выполнения
QAction *aRemontVypolneno = nullptr; // Законченные ремонты
QAction *aRemontAll2 = nullptr; // Отобразить все контура
QAction *aRemontWord1 = nullptr; // График выполнения ремонтов (документ)
QAction *aRemontWord2 = nullptr; // План капитальных/инвестиционных ремонтов (документ)
QAction *aRemontWord3 = nullptr; // План ремонтов по месяцам (документ)
QAction *aRemontAnaliz2 = nullptr; // Анализ контуров ремонта
QAction *aRemontAnaliz = nullptr; // График выполнения ремонтов
//QAction *aRemontPovrDefOtobr = nullptr; // Включить/отключить отображение объектов
//QAction *aRemontPovrOtop = nullptr; // Выбор отопительного сезона
//QAction *aRemontOsmotrTeploSet = nullptr; // Выбор фрагмента сети по Начальнику участка
QAction *aRemontVyborNach = nullptr; // Создать контур ремонта
QAction *aMarkRev = nullptr; // Добавить/удалить трубопровод к контуру
QAction *aOpresAddPlan = nullptr; // Сохранить контур плана опрессовки
QAction *aOpresSave = nullptr; // Обновить сохранение контура
QAction *aOpresGranitsaRazdela = nullptr; // Границы раздела
QAction *aListOpres = nullptr; // Список контуров опрессовок
QAction *aLastOpres = nullptr; // Последний контур опрессовки
QAction *aOpresPlan = nullptr; // Контуры планов опрессовок сезона
QAction *aOpresProcess = nullptr; // Опрессовка в процессе выполнения
QAction *aOpresVypolneno = nullptr; // Завершенные опрессовки
QAction *aOpresAll2 = nullptr; // Отобразить все контура
QAction *aOpresWord1 = nullptr; // План опрессовок (документ)
QAction *aOpresWord2 = nullptr; // График опрессовок по месяцам (документ)
QAction *aOpresAnaliz2 = nullptr; // Анализ контуров опрессовок
QAction *aOpresAnaliz = nullptr; // Анализ нарушений контура
//QAction *aRemontPovrDefOtobr = nullptr; // Включить/отключить отображение объектов
//QAction *aRemontPovrOtop = nullptr; // Выбор отопительного сезона
//QAction *aRemontOsmotrTeploSet = nullptr; // Выбор фрагмента сети по Начальнику участка
QAction *aOpresVyborNach = nullptr; // Создать контур опрессовки
//QAction *aListRemont2 = nullptr; // Список контуров ремонтов
//QAction *aMarkRev = nullptr; // Добавить/удалить трубопровод к контуру
QAction *aRemontPovrKarta = nullptr; // Карта нарушений
QAction *aRemontPovrKarta2 = nullptr; // Карта осмотра шурфа


//--

QAction *aViewToolbarRemont2 = nullptr; // Панель Контуры ремонта
QAction *aNaprRemont2 = nullptr; // Создать Контур ремонта...
//QAction *aListRemont2 = nullptr; // Выбрать Контур ремонта...
QAction *aNaprTableRemont2 = nullptr; // Таблица участков Контура ремонта...
QAction *aSaveRemont2 = nullptr; // Сохранить текущий Контур ремонта...
QAction *aSaveRemont2New = nullptr; // Сохранить новый Контур ремонта...
//QAction *aViewToolbar2Remont = nullptr; // Панель Ремонт
QAction *aRemontsAdd = nullptr; // Создать объект ремонта
QAction *aRemontsInfo = nullptr; // Информация по объекту
QAction *aRemontsTable = nullptr; // Таблица
QAction *aRemontsDel = nullptr; // Удалить объект
QAction *aZhurnalDefect = nullptr; // Повреждения
QAction *aZhurnalDiag = nullptr; // Диагностика
QAction *aZhurnalRemont = nullptr; // Ремонты
QAction *aZhurnalExcel = nullptr; // Excel
//QAction *aViewToolbarOpressovka = nullptr; // Панель Опрессовок
QAction *aNaprOpres = nullptr; // Создать Контур опрессовок...
//QAction *aListOpres = nullptr; // Выбрать Контур опрессовок...
QAction *aRemontsAddOpres = nullptr; // Создать Повреждение опрессовок...
QAction *aZhurnalDefectOpres = nullptr; // Журнал Повреждений опрессовок...
QAction *aNaprTableOpres = nullptr; // Таблица участков Контура опрессовок...
QAction *aSaveOpres = nullptr; // Сохранить текущий Контур опрессовок...
QAction *aSaveOpresNew = nullptr; // Сохранить новый Контур опрессовок...
//QAction *aViewToolbarKorrozia = nullptr; // Панель Индикаторов коррозии
QAction *aKorrozAdd = nullptr; // Установить индикатор коррозии
QAction *aKorrozDel = nullptr; // Удалить индикатор коррозии
QAction *aFragmentPolyKorroziaAr = nullptr; // Удалить выбранные индикаторы
QAction *aKorrozInfo = nullptr; // Информация по индикатору
QAction *aKorroziaUpdate = nullptr; // Выбор шаблона плана
QAction *aKorrozDoc3 = nullptr; // План установки
QAction *aKorrozTable = nullptr; // Таблица индикаторов коррозии
QAction *aKorroziaZhurnal1 = nullptr; // План индикаторов
QAction *aKorroziaZhurnal2 = nullptr; // Индикаторы установленные 
QAction *aKorroziaZhurnal3 = nullptr; // Индикаторы извлеченные
QAction *aKorroziaCurrent = nullptr; // Все индикаторы сезона
QAction *aKorrozDoc2 = nullptr; // Оценка за отопительный сезон
QAction *aKorrozDoc1 = nullptr; // Оценка за выбранные сезоны
QAction *aKorroziaOnoff = nullptr; // Включить/отключить отображение
QAction *aKorroziaSezon = nullptr; // Выбор отопительного сезона
QAction *aIznos = nullptr; // Износ оборудования
//QAction *aRemontPlan = nullptr; // Планирование ремонтов
//QAction *aViewToolbarElectro = nullptr; // Панель Электросеть
QAction *aElectroAdd = nullptr; // Установить объект
QAction *aElectroInfo = nullptr; // Информация по объекту
QAction *aElectroTable = nullptr; // Таблица
QAction *aElectroDel = nullptr; // Удалить объект
QAction *aZhurnalElectro = nullptr; // Журнал

QAction *aElectroIst = nullptr; //
QAction *aElectroPriem = nullptr; //
QAction *aElectroLine = nullptr; //
QAction *aElectroMufta = nullptr; //
QAction *aElectroOpora = nullptr; //
QAction *aElectroGil = nullptr; //
QAction *aElectroKanal = nullptr; //
QAction *aElectroZhurnal = nullptr; //
QAction *aElectroOnoff = nullptr; //


QAction *aTeplopoteri = nullptr; // Теплопотери
QAction *aColors = nullptr; // Стиль линии
QAction *aFon = nullptr; // Цвет фона
QAction *aFont2 = nullptr; // Шрифт текста
QAction *aFont = nullptr; // Шрифт надписей
QAction *aFontMag = nullptr; // Шрифт названия магистрали
QAction *aFontPanel = nullptr; // Шрифт в проводнике
QAction *aTransp = nullptr; // Прозрачность
QAction *aAstr = nullptr; // Сетка
QAction *aRamka = nullptr; // Рамка схемы
QAction *aIsMas = nullptr; // Сохранять пропорции

QAction *aSetupGid9 = nullptr; // 

QAction *aMasPic = nullptr; // Номинальный масштаб
QAction *aMasPodpis = nullptr; // Масштаб откл.надписей
QAction *aTrio = nullptr; // Передвинуть
QAction *aIndexes = nullptr; // Обновление индексов
QAction *aUpdateSetup = nullptr; // Настройка обновлений
QAction *aHttp2 = nullptr; // Веб-сервер
QAction *aExportPts = nullptr; // Экспорт фрагмента ПТС
QAction *aQuery = nullptr; // 


QAction *aImportPts = nullptr; // Импорт фрагмента ПТС
QAction *aSetAvtoOn = nullptr; // Сделать потребители автоматическими
QAction *aSetAvtoOff = nullptr; // Сделать потребители неавтоматическими
QAction *aCreateSortNode = nullptr; // Создание таблицы sortNodesForUchastok
QAction *aRasList = nullptr; // Список расчетов
QAction *aSetPsMap = nullptr; // Установить объекты ПС
QAction *aSavePng = nullptr; // Сохранить как PNG
QAction *aUtNapr2 = nullptr; // Сортировка участков
QAction *aInvert = nullptr; // Инвертировать выделение
QAction *aSetAddr = nullptr; // Адреса потребителей
QAction *aAlma = nullptr; // Паспортизация
QAction *aTuZav = nullptr; // Установить статус Завершен для ТУ
QAction *aExport = nullptr; // Экспорт гидравлики в TXT
QAction *aSetLineid = nullptr; // !
QAction *aSetIst = nullptr; // Расстановка источников
QAction *aUchList = nullptr; // Список участков ПТС
QAction *aFindcoordDeg = nullptr; // Поиск по координатам
QAction *aAsyncCheck = nullptr; // Проверка Async Task
QAction *aCheckPo = nullptr; // Проверка
QAction *aResetGeo = nullptr; // Обновить надписи
QAction *aPsAstanaName = nullptr; // Отображение имен узлов
QAction *aColorOnlyPts = nullptr; // Цвета только для участков ПТС
QAction *aExportDxf = nullptr; // Автокад DXF
QAction *aExportShape = nullptr; // ESRI shape-файлы
QAction *aPrPo = nullptr; // Реальные -> обобщенные
QAction *aUtNapr = nullptr; // Сортировка участков
QAction *aC3Del = nullptr; // Удалить внутренние схемы
QAction *aC3Add = nullptr; // Создать внутренние схемы
QAction *aIspravl = nullptr; // Восстановить файл
QAction *aOpc = nullptr; // Настройка OPC сервера
QAction *aNomap = nullptr; // Нет карты
QAction *aGoogleMap = nullptr; // Карта
QAction *aGoogleSat = nullptr; // Спутник
QAction *aGoogleHybrid = nullptr; // Гибридная
QAction *aVisicomMap = nullptr; // Карта VISICOM
QAction *aWmsMap = nullptr; // Карта WMS
QAction *aWmsCust = nullptr; // Настройка
QAction *aMapSemey = nullptr; // Семей (город)
QAction *aMapSemeyTs = nullptr; // Семей (тепловые сети)
QAction *aOpenstreetmap = nullptr; // OpenStreetMap
QAction *a2gisMap = nullptr; // 2ГИС
QAction *aEsriSatMap = nullptr; // 2ГИС
QAction *aMaptilerStreets = nullptr; // MapTiler Улицы
QAction *aMaptilerTopo = nullptr; // MapTiler Топография
QAction *aMaptilerHybrid = nullptr; // MapTiler Гибридная
QAction *aMaptilerOsm = nullptr; // MapTiler OpenStreetMap

QAction *aGoogleElevation = nullptr; // Высота по Google
QAction *aGoogleElevationSet = nullptr; // Высота по Google
QAction *aMapSearch = nullptr; // Поиск
QAction *aMapPath = nullptr; // Каталог
QAction *aMapYes = nullptr; // Восстанавливать подключение
QAction *aFileOpenOld = nullptr; // Импорт
QAction *aAddUser = nullptr; // Регистрация пользователей
QAction *aPassword = nullptr; // Изменить доступ пользователя
QAction *aPassword2 = nullptr; // Изменить пароль
QAction *aViewStatusBar = nullptr; // Строка статуса
QAction *aViewApplookWin2000 = nullptr; // Windows &2000
QAction *aViewApplookOffXp = nullptr; // Office &XP
QAction *aViewApplookWinXp = nullptr; // &Windows XP
QAction *aViewApplookOff2003 = nullptr; // Office 200&3
QAction *aViewApplookVs2005 = nullptr; // Visual Studio 200&5
QAction *aViewApplookVs2008 = nullptr; // Visual Studio 200&8
QAction *aViewApplookOff2007Blue = nullptr; // &Blue Style
QAction *aViewApplookOff2007Black = nullptr; // B&lack Style
QAction *aViewApplookOff2007Silver = nullptr; // &Silver Style
QAction *aViewApplookOff2007Aqua = nullptr; // &Aqua Style
QAction *aHelpFinder = nullptr; // Содержание\tF1
QAction *aUpdate = nullptr; // Последнее обновление
//QAction *aUpdateSetup = nullptr; // Настройка обновлений
//QAction *aAppAbout = nullptr; // О программе
//QAction *aQtAbout = nullptr; // О программе

QAction *aTuNew = nullptr; //
QAction *aTuLine = nullptr; //
QAction *aTuInfo = nullptr; //
QAction *aTuDel = nullptr; //


QAction *aSetMsNew = nullptr; //
QAction *aSetRsNew = nullptr; //
QAction *aEditFindPs = nullptr; //
QAction *aRasprMagNew = nullptr; //
QAction *aMagNode = nullptr; //
QAction *aNapr2 = nullptr; //
QAction *aVyd4 = nullptr; //
//QAction *aNapr2 = nullptr; //
QAction *aMarkDel = nullptr; //
QAction *aMsNode1 = nullptr; //
QAction *aMsNode2 = nullptr; //
QAction *aSaveMAG = nullptr; //
QAction *aSaveMS = nullptr; //
QAction *aSaveRS = nullptr; //
QAction *aMsPassport = nullptr; //
QAction *aAktCreate = nullptr; //
QAction *aPassportOnOff = nullptr; //
QAction *aPtsZhurnal = nullptr; //


QAction *aSelect6 = nullptr;   // "Выделить",  ":/images/new/5/select-window 1.svg");
QAction *aExport6 = nullptr;   //  "Экспорт",   ":/images/new/6/export.svg");
QAction *aRezhim6 = nullptr;   //  "Режим",   ":/images/new/6/switch-double-svgrepo-com 1.svg");
QAction *aSetup6 = nullptr;   //  "Настройка", ":/images/new/6/setup.svg");
QAction *aFile6 = nullptr;   //  "Файл", "");
QAction *aGeobaza6 = nullptr;   //  "Геобаза", ":/images/new/6/setup.svg");
QAction *aFind6 = nullptr;   //  


QAction *aNagrAlmatyTable = nullptr; // Объекты АЛСЕКО
QAction *aNagrAlmatyAdd1 = nullptr; // Добавить Объект (МЖД) АЛСЕКО
QAction *aNagrAlmatyAdd2 = nullptr; // Добавить Объект (Прочие) АЛСЕКО
QAction *aNagrAlmaty = nullptr; // Объекты АЛСЕКО по адресам
QAction *aNagrAlmatyOnOff = nullptr; // Вывести нагрузки АЛСЕКО
QAction *aNagrAlmaXlsx = nullptr; // Реестр объектов АЛСЕКО
QAction *aNagrAlmaNenaid1 = nullptr; // Реестр ненайденных объектов (МЖД) АЛСЕКО
QAction *aNagrAlmaNenaid2 = nullptr; // Реестр ненайденных объектов (Прочие) АЛСЕКО
QAction *aNagrAlmaNenaid3 = nullptr; // Здания АЛСЕКО без потребителя


//-----------------------------------

QAction *aFindcoord = nullptr;
QAction *aEsc = nullptr;
//QAction *aMarkRev = nullptr;


//-----------------------------------


QShortcut *cAstr = nullptr;
QShortcut *cDel = nullptr;
QShortcut *cEditCopy = nullptr;

QShortcut *cEditFindNode = nullptr;
QShortcut *cF4 = nullptr;
QShortcut *cF5 = nullptr;
QShortcut *cCtrlF5 = nullptr;
QShortcut *cFilePrint = nullptr;

QShortcut *cFindcoord = nullptr;

QShortcut *cFindcoordDeg = nullptr;
QShortcut *cHelpFinder = nullptr;
QShortcut *cInfo = nullptr;
QShortcut *cLine = nullptr;

QShortcut *cMasall = nullptr;
QShortcut *cMasshtab = nullptr;
QShortcut *cMinus = nullptr;
QShortcut *cMovew = nullptr;
QShortcut *cNode = nullptr;
QShortcut *cNodeMove = nullptr;
QShortcut *cPlus = nullptr;
QShortcut *cZoom = nullptr;
QShortcut *cNodeNeotr = nullptr;



};
