#define ST_BP "Байпас"
#define ST_CT "Система теплоснабжения"
#define ST_DR "Диафрагма"
#define ST_EL "Элеватор"
#define ST_HC "Насосный агрегат"
#define ST_HS "Насосная станция"
#define ST_C3 "Клапан трехходовой"
#define ST_IS "Источник тепла"
#define ST_KL "Канал"
#define ST_KM "Компенсатор"
#define ST_KU "Калориферная установка"
#define ST_KV "Коэффициенты вариации"
#define ST_MT "Манометр"
#define ST_OK "Обратный клапан"
#define ST_OP "Опора"
#define ST_OR "Организация"
#define ST_PC "Расчетная схема"
#define ST_PO "Потребитель обобщенный"
#define ST_PR "Потребитель реальный"
#define ST_RA "Радиаторы системы отопления"
#define ST_RD "Регулятор давления"
#define ST_RN "Район эксплуатации"
#define ST_RR "Регулятор расхода"
#define ST_TE "Термометр"
#define ST_TP "Теплообменник"
#define ST_TL "Теплообменник пластинчатый"
#define ST_TT "Теплообменник трубчатый"
#define ST_UP "Узел подпитки"
#define ST_UR "Удельные расходы"
#define ST_US "Узел"
#define ST_US2 "Узел присоединения"
#define ST_UT "Участок теплопровода"
#define ST_V1 "Местные сопротивления участка трубопровода"
#define ST_ZD "Задвижка"
#define ST_ZE "Здание"
#define ST_ZN "Узел с заданным напором"
#define ST_ZP "ЦТП"
#define ST_VP "Водоразборный прибор"


#define ST_BP_RES "BP_OUT"
#define ST_NS_RES "NS_OUT"
#define ST_PT_RES "PT_OUT"
#define ST_RS_RES "RS_OUT"
#define ST_US_RES "US_OUT"
#define ST_UT_RES "UT_OUT"
#define ST_OK_RES "OK_OUT"
#define ST_PT_RES "PT_OUT"
#define ST_ZD_RES "ZD_OUT"
#define ST_ZD2_RES "ZD2_OUT"
#define ST_DR_RES "DR_OUT"
#define ST_DRO_RES "DRO_OUT"

#define ST_BP_RES_NAME "Байпасы наружних теплопроводов"
#define ST_NS_RES_NAME "Насосные агрегаты"
#define ST_PT_RES_NAME "Потребители"
#define ST_RS_RES_NAME "Сетевые регуляторы"
#define ST_US_RES_NAME "Узлы системы"
#define ST_UT_RES_NAME "Участки теплопроводов"
#define ST_OK_RES_NAME "Обратные клапаны"
#define ST_ZD_RES_NAME "Задвижки"
#define ST_ZD2_RES_NAME "Регулирующая арматура"
#define ST_DR_RES_NAME "Дроссельные органы потребителей"
#define ST_DRO_RES_NAME "Диафрагмы"
#define ST_PTOFF_RES_NAME "Потребители отключенные "
