const char *ppp = 
"t.ID,"
//"Sostoyanie_dogovora,"
"st.name AS Sostoyanie_dogovora,"
"Nomer_TU,"
"Data_vydachi_TU,"
"Naimenovanie_organizatsii__zaprashivayuschey_TU,"
"Naimenovanie_obekta,"
"Adres_obekta,"
"Istochnik,"
"Rayon_ekspluatatsii,"
"Teplovye_potoki__Gkal_ch,"
"V_tom_chisle_otoplenie,"
"V_tom_chisle_ventilyatsiya,"
"V_tom_chisle_GVS_maks,"
"Prirost_nagruzki,"
"V_tom_chisle_prirost_otoplenie,"
"V_tom_chisle_prirost_ventilyatsiya,"
"V_tom_chisle_prirost_GVS_maks,"
"Nomer_soglasovaniya_TS,"
"Data_soglasovaniya_TS,"
"Nomer_soglasovaniya_OV,"
"Data_soglasovaniya_OV,"
"Nomer_soglasovaniya_TP,"
"Data_soglasovaniya_TP,"
"Ispolnenie_dop_tehn_i_energ_meropriyatiy_v_ramkah_TU,"
"Stadiya_stroitelstva_obektov,"
"Nomer_vydachi_akta_dopuska,"
"Data_vydachi_akta_dopuska,"
"Teplovaya_nagruzka_po_aktu_dopuska__proektu__Gkal_ch,"
"V_tom_chisle_otoplenie_po_aktu,"
"V_tom_chisle_ventilyatsiya_po_aktu,"
"V_tom_chisle_GVS_maks_po_aktu,"
"Nomer_dogovora,"
"Data_dogovora,"
"Zdanie"

;


const char *ppp2 =
"'',"
"'',"
"'Итого',"
"'',"
"'',"
"'',"
"'',"
"'',"
"'',"
"sum(Teplovye_potoki__Gkal_ch),"
"sum(V_tom_chisle_otoplenie),"
"sum(V_tom_chisle_ventilyatsiya),"
"sum(V_tom_chisle_GVS_maks),"
"sum(Prirost_nagruzki),"
"sum(V_tom_chisle_prirost_otoplenie),"
"sum(V_tom_chisle_prirost_ventilyatsiya),"
"sum(V_tom_chisle_prirost_GVS_maks),"
"'',"
"'',"
"'',"
"'',"
"'',"
"'',"
"'',"
"'',"
"'',"
"'',"
"sum(Teplovaya_nagruzka_po_aktu_dopuska__proektu__Gkal_ch),"
"sum(V_tom_chisle_otoplenie_po_aktu),"
"sum(V_tom_chisle_ventilyatsiya_po_aktu),"
"sum(V_tom_chisle_GVS_maks_po_aktu),"
"'',"
"'',"
"0"

;

