#pragma once

#define WM_USER_FIND_ZH (WM_USER + 5)
#define WM_USER_FIND_ZD (WM_USER + 6)
#define WM_USER_FIND_SEL_GEO_OBJECT (WM_USER + 7)
#define WM_USER_FIND_NODE (WM_USER + 8)
#define WM_USER_FIND_LINE (WM_USER + 9)
#define WM_USER_FIND_LINE_BIG (WM_USER + 10)
#define WM_USER_FIND_LINE_BIG2 (WM_USER + 12)
#define WM_USER_FIND_GEO (WM_USER + 13)
#define WM_USER_FIND_GEO_BIG_LINE (WM_USER + 13)
#define WM_USER_FIND_GEO_EDIT (WM_USER + 14)
#define WM_USER_FIND_LINE_BIG_OSMOTR (WM_USER + 15)
#define WM_USER_FIND_GEO_TU (WM_USER + 16)

#define WM_USER_ALSECO1_UPDATED (WM_USER + 17)
#define WM_USER_ALSECO2_UPDATED (WM_USER + 18)



#define WM_STATUS (WM_USER+201)

#define WM_LDBL (WM_USER+201)
#define WM_TABLE_CHANGE (WM_USER+203)
#define WM_SET_OUT (WM_USER+204)
#define WM_LCLICK (WM_USER+205)


#define WM_USER_ADO_UPDATED (WM_USER + 1001)
#define WM_USER_ADO_NOUPDATED (WM_USER + 1002)

#define WM_USER_MAP_SEARCH (WM_USER + 1003)

#define WM_USER_OPRES WM_USER + 1004
#define WM_USER_OPRES_EDIT WM_USER + 1005
#define WM_KORROZIA_UPDATED + 1006



#define WM_USER_COORD_UPDATED WM_USER + 5126



#define WM_USER_REFRESH (WM_USER + 5127)


#define WM_USER_SHURF_UTVERDIT WM_USER + 5128
#define WM_USER_SHURF_UTVERDIT_ALL WM_USER + 5129
#define WM_USER_REMONT_UTVERDIT WM_USER + 5130
#define WM_USER_TABLE_OPEN_FILE_DIALOG WM_USER + 5131


#define WM_PROCESS_COMPLETE  WM_USER + 6001

