#define ST_BP "Байпас"
#define ST_CT "Система теплоснабжения"
#define ST_DR "Диафрагма"
#define ST_EL "Элеватор"
#define ST_HC "Насосный агрегат"
#define ST_HS "Насосная станция"
#define ST_C3 "Клапан трехходовой"
#define ST_IS "Источник тепла"
#define ST_KL "Канал"
#define ST_KM "Компенсатор"
#define ST_KU "Калориферная установка"
#define ST_KV "Коэффициенты вариации"
#define ST_MT "Манометр"
#define ST_OK "Обратный клапан"
#define ST_OP "Опора"
#define ST_OR "Организация"
#define ST_PC "Расчетная схема"
#define ST_PO "Потребитель обобщенный"
#define ST_RO "Радиаторы системы отопления"
#define ST_PR "Потребитель реальный"
#define ST_RD "Регулятор давления"
#define ST_RP "Регулятор перепада давления"
#define ST_RN "Район эксплуатации"
#define ST_RR "Регулятор расхода"
#define ST_TE "Термометр"
#define ST_TO "Теплообменник"
#define ST_TL "Теплообменник пластинчатый"
#define ST_TT "Теплообменник трубчатый"
#define ST_UP "Узел подпитки"
#define ST_UR "Удельные расходы"
#define ST_US "Узел"
#define ST_US2 "Узел присоединения"
#define ST_UT "Участок теплопровода"
#define ST_UT_KAP1 "Капремонт Участок теплопровода исходный"
#define ST_UT_KAP2 "Капремонт Участок теплопровода после ремонта"

#define ST_UT_OPR1 "Опрессовка Участок теплопровода исходный"
#define ST_UT_OPR2 "Опрессовка Участок теплопровода после ремонта"


#define ST_V1 "Местные сопротивления участка трубопровода"
#define ST_VP "Водоразборный прибор"
#define ST_ZD "Задвижка"
#define ST_ZD2 "Регулирующая арматура"
#define ST_ZE "Здание"
#define ST_ZN "Узел с заданным напором"
#define ST_ORP "Объекты с измеряемыми параметрами"
#define ST_PRIBOR "Прибор учета тепловой энергии"
#define ST_ZP "ЦТП"

//#define STR_REMONT "Журнал_Ремонт_трубы_камеры"
#define STR_REMONT_DEFECT "Дефект"
#define STR_REMONT_DEFECT2 "Дефект2"
#define STR_REMONT_SHURF "Шурф"
#define STR_REMONT_SHURF2 "Шурф2"
#define STR_REMONT_OSMOTR "Осмотр"
#define STR_REMONT_KORROZ "Индикатор_коррозии"
//#define STR_REMONT_KORROZ "corrosionIndicators"

#define STR_REMONT_ISPYT  "Испытания"
#define STR_REMONT_KAPITAL "Капремонт_участки_ремонта"
#define STR_REMONT_CONTROL_TU "Контроль технического состояния"
//#define STR_REMONT_OPRESSOVKA "Опрессовка_участки_ремонта"

//#define STR_PASPORT_OBJ "Паспорт объекта теплоснабжения"
#define STR_PASPORT_OBJ "passports"

#define STR_TRUB_REKONSTR "Трубы реконструируемые"
