-- СГЕНЕРИРОВАНО tools/gen_read_sql.py
--
-- Замена us.sql для схемы net. Набор возвращаемых колонок совпадает
-- с прежним, поэтому приложение менять не требуется — достаточно
-- подложить этот файл вместо старого.
--
-- Запрос заканчивается WHERE: приложение дописывает
--   AND n.fileID IN (...)
-- конкатенацией строки.

SELECT
    n.id,
    n.fileid,
    n.internalnodeid,
    n.externalcodeid,
    n.externalsignid,
    n.displaysign,
    n.x,
    n.y,
    n.nodetypeid,
    n.externalnodename,
    n.nodename,
    n.geomarktoptube,
    n.geomarknodearea,
    n.calcpressflow,
    n.calcpressret,
    n.consumerstateid,
    n.hz,
    pt_out.id AS nompt,
    n.connectid,
    n.automdegid,
    n.calchldep,
    n.calchlindep,
    n.calchlventil,
    n.calchlparall,
    n.calchlgvsparall,
    n.avghlcompparall,
    n.calchlmix,
    n.calchlgvsmix,
    n.avghlcompmix,
    n.calchlconseq,
    n.calchlgvsconseq,
    n.avghlcompconseq,
    n.calchlpreon,
    n.calchlgvspreon,
    n.avghlcomppreon,
    n.avghlgvsopensysflow,
    n.avghlgvsopensysret,
    n.avghlcompopen,
    n.calcinternhd,
    n.expendhwpart,
    n.avghlcond,
    n.avghlclosesys,
    n.avghlopensysflow,
    n.avghlopensysret,
    n.avghlgvsopenflow,
    n.avghlgvsopenret,
    n.avghlgvscloseparall,
    n.avghlgvsclosemix,
    n.avghlgvscloseconseq,
    n.avghlgvsclosepreon,
    n.wemeteringdeviceid,
    usp.id AS uspid,
    uso.id AS usoid,
    usp.calculationid AS calculationidp,
    uso.calculationid AS calculationido,
    usp.pih AS pihp,
    uso.pih AS piho,
    usp.t AS tp1,
    uso.t AS to1,
    pt_out.a15,
    pt_out.a16,
    pt_out.a17,
    CASE WHEN pt_out.a3 = 'Закрыта' THEN 1 ELSE 0 END AS iszakr,
    dr_out.id AS nomdr,
    n.schemenum,
    n.id2,
    n.type_txt
FROM (
SELECT
    consumer_real.src_id AS id,
    consumer_real.fragment_id AS fileid,
    consumer_real.internalnodeid,
    consumer_real.externalcodeid,
    consumer_real.externalsignid,
    consumer_real.displaysign,
    ST_X(ST_StartPoint(consumer_real.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(consumer_real.geom)) * 100.0 AS y,
    consumer_real.nodetypeid,
    consumer_real.externalnodename,
    consumer_real.nodename,
    consumer_real.geomarktoptube,
    consumer_real.geomarknodearea,
    consumer_real.calcpressflow,
    consumer_real.calcpressret,
    consumer_real.consumerstateid AS consumerstateid,
    consumer_real.buildheight AS hz,
    NULL::integer AS connectid,
    consumer_real.automdegid,
    consumer_real.calchldep,
    consumer_real.calchlindep,
    consumer_real.calchlventil,
    NULL::double precision AS calchlparall,
    NULL::double precision AS calchlgvsparall,
    NULL::double precision AS avghlcompparall,
    NULL::double precision AS calchlmix,
    NULL::double precision AS calchlgvsmix,
    NULL::double precision AS avghlcompmix,
    NULL::double precision AS calchlconseq,
    NULL::double precision AS calchlgvsconseq,
    NULL::double precision AS avghlcompconseq,
    NULL::double precision AS calchlpreon,
    NULL::double precision AS calchlgvspreon,
    NULL::double precision AS avghlcomppreon,
    NULL::double precision AS avghlgvsopensysflow,
    NULL::double precision AS avghlgvsopensysret,
    NULL::double precision AS avghlcompopen,
    consumer_real.calcinternhd,
    consumer_real.expendhwpart,
    consumer_real.avghlcond,
    consumer_real.avghlclosesys,
    consumer_real.avghlopensysflow,
    consumer_real.avghlopensysret,
    consumer_real.avghlgvsopenflow,
    consumer_real.avghlgvsopenret,
    consumer_real.avghlgvscloseparall,
    consumer_real.avghlgvsclosemix,
    consumer_real.avghlgvscloseconseq,
    consumer_real.avghlgvsclosepreon,
    consumer_real.wemeteringdeviceid,
    consumer_real.schemenum,
    consumer_real.id AS id2,
    'PR' AS type_txt,
    0 AS removed
FROM net.consumer_real consumer_real
WHERE consumer_real.removed_at IS NULL
UNION ALL
SELECT
    consumer_general.src_id AS id,
    consumer_general.fragment_id AS fileid,
    consumer_general.internalnodeid,
    consumer_general.externalcodeid,
    consumer_general.externalsignid,
    consumer_general.displaysign,
    ST_X(ST_StartPoint(consumer_general.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(consumer_general.geom)) * 100.0 AS y,
    consumer_general.nodetypeid,
    consumer_general.externalnodename,
    consumer_general.nodename,
    consumer_general.geomarktoptube,
    consumer_general.geomarknodearea,
    consumer_general.calcpressflow,
    consumer_general.calcpressret,
    consumer_general.consumerstateid AS consumerstateid,
    consumer_general.maxbuildingheight AS hz,
    NULL::integer AS connectid,
    NULL::integer AS automdegid,
    consumer_general.calchldep,
    consumer_general.calchlindep,
    consumer_general.calchlventil,
    consumer_general.calchlparall,
    consumer_general.calchlgvsparall,
    consumer_general.avghlcompparall,
    consumer_general.calchlmix,
    consumer_general.calchlgvsmix,
    consumer_general.avghlcompmix,
    consumer_general.calchlconseq,
    consumer_general.calchlgvsconseq,
    consumer_general.avghlcompconseq,
    consumer_general.calchlpreon,
    consumer_general.calchlgvspreon,
    consumer_general.avghlcomppreon,
    consumer_general.avghlgvsopensysflow,
    consumer_general.avghlgvsopensysret,
    consumer_general.avghlcompopen,
    NULL::double precision AS calcinternhd,
    consumer_general.expendhwpart,
    NULL::double precision AS avghlcond,
    NULL::double precision AS avghlclosesys,
    NULL::double precision AS avghlopensysflow,
    NULL::double precision AS avghlopensysret,
    NULL::double precision AS avghlgvsopenflow,
    NULL::double precision AS avghlgvsopenret,
    NULL::double precision AS avghlgvscloseparall,
    NULL::double precision AS avghlgvsclosemix,
    NULL::double precision AS avghlgvscloseconseq,
    NULL::double precision AS avghlgvsclosepreon,
    consumer_general.wemeteringdeviceid,
    NULL::text AS schemenum,
    consumer_general.id AS id2,
    'PO' AS type_txt,
    0 AS removed
FROM net.consumer_general consumer_general
WHERE consumer_general.removed_at IS NULL
UNION ALL
SELECT
    heat_source.src_id AS id,
    heat_source.fragment_id AS fileid,
    heat_source.internalnodeid,
    heat_source.externalcodeid,
    heat_source.externalsignid,
    heat_source.displaysign,
    ST_X(ST_StartPoint(heat_source.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(heat_source.geom)) * 100.0 AS y,
    heat_source.nodetypeid,
    heat_source.externalnodename,
    heat_source.nodename,
    heat_source.geomarktoptube,
    heat_source.geomarknodearea,
    heat_source.calcpressflow,
    heat_source.calcpressret,
    1 AS consumerstateid,
    NULL::double precision AS hz,
    NULL::integer AS connectid,
    NULL::integer AS automdegid,
    NULL::double precision AS calchldep,
    NULL::double precision AS calchlindep,
    NULL::double precision AS calchlventil,
    NULL::double precision AS calchlparall,
    NULL::double precision AS calchlgvsparall,
    NULL::double precision AS avghlcompparall,
    NULL::double precision AS calchlmix,
    NULL::double precision AS calchlgvsmix,
    NULL::double precision AS avghlcompmix,
    NULL::double precision AS calchlconseq,
    NULL::double precision AS calchlgvsconseq,
    NULL::double precision AS avghlcompconseq,
    NULL::double precision AS calchlpreon,
    NULL::double precision AS calchlgvspreon,
    NULL::double precision AS avghlcomppreon,
    NULL::double precision AS avghlgvsopensysflow,
    NULL::double precision AS avghlgvsopensysret,
    NULL::double precision AS avghlcompopen,
    NULL::double precision AS calcinternhd,
    NULL::double precision AS expendhwpart,
    NULL::double precision AS avghlcond,
    NULL::double precision AS avghlclosesys,
    NULL::double precision AS avghlopensysflow,
    NULL::double precision AS avghlopensysret,
    NULL::double precision AS avghlgvsopenflow,
    NULL::double precision AS avghlgvsopenret,
    NULL::double precision AS avghlgvscloseparall,
    NULL::double precision AS avghlgvsclosemix,
    NULL::double precision AS avghlgvscloseconseq,
    NULL::double precision AS avghlgvsclosepreon,
    NULL::integer AS wemeteringdeviceid,
    NULL::text AS schemenum,
    heat_source.id AS id2,
    'IS' AS type_txt,
    0 AS removed
FROM net.heat_source heat_source
WHERE heat_source.removed_at IS NULL
UNION ALL
SELECT
    pump_station.src_id AS id,
    pump_station.fragment_id AS fileid,
    pump_station.internalnodeid,
    pump_station.externalcodeid,
    pump_station.externalsignid,
    pump_station.displaysign,
    ST_X(ST_StartPoint(pump_station.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(pump_station.geom)) * 100.0 AS y,
    pump_station.nodetypeid,
    pump_station.externalnodename,
    pump_station.nodename,
    pump_station.geomarktoptube,
    pump_station.geomarknodearea,
    pump_station.calcpressflow,
    pump_station.calcpressret,
    1 AS consumerstateid,
    NULL::double precision AS hz,
    NULL::integer AS connectid,
    NULL::integer AS automdegid,
    NULL::double precision AS calchldep,
    NULL::double precision AS calchlindep,
    NULL::double precision AS calchlventil,
    NULL::double precision AS calchlparall,
    NULL::double precision AS calchlgvsparall,
    NULL::double precision AS avghlcompparall,
    NULL::double precision AS calchlmix,
    NULL::double precision AS calchlgvsmix,
    NULL::double precision AS avghlcompmix,
    NULL::double precision AS calchlconseq,
    NULL::double precision AS calchlgvsconseq,
    NULL::double precision AS avghlcompconseq,
    NULL::double precision AS calchlpreon,
    NULL::double precision AS calchlgvspreon,
    NULL::double precision AS avghlcomppreon,
    NULL::double precision AS avghlgvsopensysflow,
    NULL::double precision AS avghlgvsopensysret,
    NULL::double precision AS avghlcompopen,
    NULL::double precision AS calcinternhd,
    NULL::double precision AS expendhwpart,
    NULL::double precision AS avghlcond,
    NULL::double precision AS avghlclosesys,
    NULL::double precision AS avghlopensysflow,
    NULL::double precision AS avghlopensysret,
    NULL::double precision AS avghlgvsopenflow,
    NULL::double precision AS avghlgvsopenret,
    NULL::double precision AS avghlgvscloseparall,
    NULL::double precision AS avghlgvsclosemix,
    NULL::double precision AS avghlgvscloseconseq,
    NULL::double precision AS avghlgvsclosepreon,
    NULL::integer AS wemeteringdeviceid,
    NULL::text AS schemenum,
    pump_station.id AS id2,
    'HS' AS type_txt,
    0 AS removed
FROM net.pump_station pump_station
WHERE pump_station.removed_at IS NULL
UNION ALL
SELECT
    valve_3way.src_id AS id,
    valve_3way.fragment_id AS fileid,
    valve_3way.internalnodeid,
    valve_3way.externalcodeid,
    valve_3way.externalsignid,
    valve_3way.displaysign,
    ST_X(ST_StartPoint(valve_3way.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(valve_3way.geom)) * 100.0 AS y,
    valve_3way.nodetypeid,
    valve_3way.externalnodename,
    valve_3way.nodename,
    valve_3way.geomarktoptube,
    valve_3way.geomarknodearea,
    valve_3way.calcpressflow,
    valve_3way.calcpressret,
    1 AS consumerstateid,
    NULL::double precision AS hz,
    NULL::integer AS connectid,
    NULL::integer AS automdegid,
    NULL::double precision AS calchldep,
    NULL::double precision AS calchlindep,
    NULL::double precision AS calchlventil,
    NULL::double precision AS calchlparall,
    NULL::double precision AS calchlgvsparall,
    NULL::double precision AS avghlcompparall,
    NULL::double precision AS calchlmix,
    NULL::double precision AS calchlgvsmix,
    NULL::double precision AS avghlcompmix,
    NULL::double precision AS calchlconseq,
    NULL::double precision AS calchlgvsconseq,
    NULL::double precision AS avghlcompconseq,
    NULL::double precision AS calchlpreon,
    NULL::double precision AS calchlgvspreon,
    NULL::double precision AS avghlcomppreon,
    NULL::double precision AS avghlgvsopensysflow,
    NULL::double precision AS avghlgvsopensysret,
    NULL::double precision AS avghlcompopen,
    NULL::double precision AS calcinternhd,
    NULL::double precision AS expendhwpart,
    NULL::double precision AS avghlcond,
    NULL::double precision AS avghlclosesys,
    NULL::double precision AS avghlopensysflow,
    NULL::double precision AS avghlopensysret,
    NULL::double precision AS avghlgvsopenflow,
    NULL::double precision AS avghlgvsopenret,
    NULL::double precision AS avghlgvscloseparall,
    NULL::double precision AS avghlgvsclosemix,
    NULL::double precision AS avghlgvscloseconseq,
    NULL::double precision AS avghlgvsclosepreon,
    NULL::integer AS wemeteringdeviceid,
    NULL::text AS schemenum,
    valve_3way.id AS id2,
    'C3' AS type_txt,
    0 AS removed
FROM net.valve_3way valve_3way
WHERE valve_3way.removed_at IS NULL
UNION ALL
SELECT
    connect_node.src_id AS id,
    connect_node.fragment_id AS fileid,
    connect_node.internalnodeid,
    connect_node.externalcodeid,
    connect_node.externalsignid,
    connect_node.displaysign,
    ST_X(ST_StartPoint(connect_node.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(connect_node.geom)) * 100.0 AS y,
    connect_node.nodetypeid,
    connect_node.externalnodename,
    connect_node.nodename,
    connect_node.geomarktoptube,
    connect_node.geomarknodearea,
    connect_node.calcpressflow,
    connect_node.calcpressret,
    1 AS consumerstateid,
    NULL::double precision AS hz,
    connect_node.connectid,
    NULL::integer AS automdegid,
    NULL::double precision AS calchldep,
    NULL::double precision AS calchlindep,
    NULL::double precision AS calchlventil,
    NULL::double precision AS calchlparall,
    NULL::double precision AS calchlgvsparall,
    NULL::double precision AS avghlcompparall,
    NULL::double precision AS calchlmix,
    NULL::double precision AS calchlgvsmix,
    NULL::double precision AS avghlcompmix,
    NULL::double precision AS calchlconseq,
    NULL::double precision AS calchlgvsconseq,
    NULL::double precision AS avghlcompconseq,
    NULL::double precision AS calchlpreon,
    NULL::double precision AS calchlgvspreon,
    NULL::double precision AS avghlcomppreon,
    NULL::double precision AS avghlgvsopensysflow,
    NULL::double precision AS avghlgvsopensysret,
    NULL::double precision AS avghlcompopen,
    NULL::double precision AS calcinternhd,
    NULL::double precision AS expendhwpart,
    NULL::double precision AS avghlcond,
    NULL::double precision AS avghlclosesys,
    NULL::double precision AS avghlopensysflow,
    NULL::double precision AS avghlopensysret,
    NULL::double precision AS avghlgvsopenflow,
    NULL::double precision AS avghlgvsopenret,
    NULL::double precision AS avghlgvscloseparall,
    NULL::double precision AS avghlgvsclosemix,
    NULL::double precision AS avghlgvscloseconseq,
    NULL::double precision AS avghlgvsclosepreon,
    NULL::integer AS wemeteringdeviceid,
    NULL::text AS schemenum,
    connect_node.id AS id2,
    'US2' AS type_txt,
    0 AS removed
FROM net.connect_node connect_node
WHERE connect_node.removed_at IS NULL
UNION ALL
SELECT
    heat_chamber.src_id AS id,
    heat_chamber.fragment_id AS fileid,
    heat_chamber.internalnodeid,
    heat_chamber.externalcodeid,
    heat_chamber.externalsignid,
    heat_chamber.displaysign,
    ST_X(ST_StartPoint(heat_chamber.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(heat_chamber.geom)) * 100.0 AS y,
    heat_chamber.nodetypeid,
    heat_chamber.externalnodename,
    heat_chamber.nodename,
    heat_chamber.geomarktoptube,
    heat_chamber.geomarknodearea,
    heat_chamber.calcpressflow,
    heat_chamber.calcpressret,
    1 AS consumerstateid,
    NULL::double precision AS hz,
    NULL::integer AS connectid,
    NULL::integer AS automdegid,
    NULL::double precision AS calchldep,
    NULL::double precision AS calchlindep,
    NULL::double precision AS calchlventil,
    NULL::double precision AS calchlparall,
    NULL::double precision AS calchlgvsparall,
    NULL::double precision AS avghlcompparall,
    NULL::double precision AS calchlmix,
    NULL::double precision AS calchlgvsmix,
    NULL::double precision AS avghlcompmix,
    NULL::double precision AS calchlconseq,
    NULL::double precision AS calchlgvsconseq,
    NULL::double precision AS avghlcompconseq,
    NULL::double precision AS calchlpreon,
    NULL::double precision AS calchlgvspreon,
    NULL::double precision AS avghlcomppreon,
    NULL::double precision AS avghlgvsopensysflow,
    NULL::double precision AS avghlgvsopensysret,
    NULL::double precision AS avghlcompopen,
    NULL::double precision AS calcinternhd,
    NULL::double precision AS expendhwpart,
    NULL::double precision AS avghlcond,
    NULL::double precision AS avghlclosesys,
    NULL::double precision AS avghlopensysflow,
    NULL::double precision AS avghlopensysret,
    NULL::double precision AS avghlgvsopenflow,
    NULL::double precision AS avghlgvsopenret,
    NULL::double precision AS avghlgvscloseparall,
    NULL::double precision AS avghlgvsclosemix,
    NULL::double precision AS avghlgvscloseconseq,
    NULL::double precision AS avghlgvsclosepreon,
    NULL::integer AS wemeteringdeviceid,
    NULL::text AS schemenum,
    heat_chamber.id AS id2,
    'US' AS type_txt,
    0 AS removed
FROM net.heat_chamber heat_chamber
WHERE heat_chamber.removed_at IS NULL
UNION ALL
SELECT
    regulator_press.src_id AS id,
    regulator_press.fragment_id AS fileid,
    regulator_press.internalnodeid,
    NULL::integer AS externalcodeid,
    NULL::integer AS externalsignid,
    regulator_press.displaysign,
    ST_X(ST_StartPoint(regulator_press.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(regulator_press.geom)) * 100.0 AS y,
    NULL::integer AS nodetypeid,
    NULL::text AS externalnodename,
    NULL::text AS nodename,
    NULL::double precision AS geomarktoptube,
    NULL::double precision AS geomarknodearea,
    NULL::double precision AS calcpressflow,
    NULL::double precision AS calcpressret,
    1 AS consumerstateid,
    NULL::double precision AS hz,
    NULL::integer AS connectid,
    NULL::integer AS automdegid,
    NULL::double precision AS calchldep,
    NULL::double precision AS calchlindep,
    NULL::double precision AS calchlventil,
    NULL::double precision AS calchlparall,
    NULL::double precision AS calchlgvsparall,
    NULL::double precision AS avghlcompparall,
    NULL::double precision AS calchlmix,
    NULL::double precision AS calchlgvsmix,
    NULL::double precision AS avghlcompmix,
    NULL::double precision AS calchlconseq,
    NULL::double precision AS calchlgvsconseq,
    NULL::double precision AS avghlcompconseq,
    NULL::double precision AS calchlpreon,
    NULL::double precision AS calchlgvspreon,
    NULL::double precision AS avghlcomppreon,
    NULL::double precision AS avghlgvsopensysflow,
    NULL::double precision AS avghlgvsopensysret,
    NULL::double precision AS avghlcompopen,
    NULL::double precision AS calcinternhd,
    NULL::double precision AS expendhwpart,
    NULL::double precision AS avghlcond,
    NULL::double precision AS avghlclosesys,
    NULL::double precision AS avghlopensysflow,
    NULL::double precision AS avghlopensysret,
    NULL::double precision AS avghlgvsopenflow,
    NULL::double precision AS avghlgvsopenret,
    NULL::double precision AS avghlgvscloseparall,
    NULL::double precision AS avghlgvsclosemix,
    NULL::double precision AS avghlgvscloseconseq,
    NULL::double precision AS avghlgvsclosepreon,
    NULL::integer AS wemeteringdeviceid,
    NULL::text AS schemenum,
    regulator_press.id AS id2,
    'US' AS type_txt,
    0 AS removed
FROM net.regulator_press regulator_press
WHERE regulator_press.removed_at IS NULL
UNION ALL
SELECT
    refill_node.src_id AS id,
    refill_node.fragment_id AS fileid,
    refill_node.internalnodeid,
    refill_node.externalcodeid,
    refill_node.externalsignid,
    refill_node.displaysign,
    ST_X(ST_StartPoint(refill_node.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(refill_node.geom)) * 100.0 AS y,
    refill_node.nodetypeid,
    refill_node.externalnodename,
    refill_node.nodename,
    refill_node.geomarktoptube,
    refill_node.geomarknodearea,
    refill_node.calcpressflow,
    refill_node.calcpressret,
    1 AS consumerstateid,
    NULL::double precision AS hz,
    NULL::integer AS connectid,
    NULL::integer AS automdegid,
    NULL::double precision AS calchldep,
    NULL::double precision AS calchlindep,
    NULL::double precision AS calchlventil,
    NULL::double precision AS calchlparall,
    NULL::double precision AS calchlgvsparall,
    NULL::double precision AS avghlcompparall,
    NULL::double precision AS calchlmix,
    NULL::double precision AS calchlgvsmix,
    NULL::double precision AS avghlcompmix,
    NULL::double precision AS calchlconseq,
    NULL::double precision AS calchlgvsconseq,
    NULL::double precision AS avghlcompconseq,
    NULL::double precision AS calchlpreon,
    NULL::double precision AS calchlgvspreon,
    NULL::double precision AS avghlcomppreon,
    NULL::double precision AS avghlgvsopensysflow,
    NULL::double precision AS avghlgvsopensysret,
    NULL::double precision AS avghlcompopen,
    NULL::double precision AS calcinternhd,
    NULL::double precision AS expendhwpart,
    NULL::double precision AS avghlcond,
    NULL::double precision AS avghlclosesys,
    NULL::double precision AS avghlopensysflow,
    NULL::double precision AS avghlopensysret,
    NULL::double precision AS avghlgvsopenflow,
    NULL::double precision AS avghlgvsopenret,
    NULL::double precision AS avghlgvscloseparall,
    NULL::double precision AS avghlgvsclosemix,
    NULL::double precision AS avghlgvscloseconseq,
    NULL::double precision AS avghlgvsclosepreon,
    NULL::integer AS wemeteringdeviceid,
    NULL::text AS schemenum,
    refill_node.id AS id2,
    'US' AS type_txt,
    0 AS removed
FROM net.refill_node refill_node
WHERE refill_node.removed_at IS NULL
UNION ALL
SELECT
    node_plain.src_id AS id,
    node_plain.fragment_id AS fileid,
    node_plain.internalnodeid,
    node_plain.externalcodeid,
    node_plain.externalsignid,
    node_plain.displaysign,
    ST_X(ST_StartPoint(node_plain.geom)) * 100.0 AS x,
    -ST_Y(ST_StartPoint(node_plain.geom)) * 100.0 AS y,
    node_plain.nodetypeid,
    node_plain.externalnodename,
    node_plain.nodename,
    node_plain.geomarktoptube,
    node_plain.geomarknodearea,
    node_plain.calcpressflow,
    node_plain.calcpressret,
    1 AS consumerstateid,
    NULL::double precision AS hz,
    NULL::integer AS connectid,
    NULL::integer AS automdegid,
    NULL::double precision AS calchldep,
    NULL::double precision AS calchlindep,
    NULL::double precision AS calchlventil,
    NULL::double precision AS calchlparall,
    NULL::double precision AS calchlgvsparall,
    NULL::double precision AS avghlcompparall,
    NULL::double precision AS calchlmix,
    NULL::double precision AS calchlgvsmix,
    NULL::double precision AS avghlcompmix,
    NULL::double precision AS calchlconseq,
    NULL::double precision AS calchlgvsconseq,
    NULL::double precision AS avghlcompconseq,
    NULL::double precision AS calchlpreon,
    NULL::double precision AS calchlgvspreon,
    NULL::double precision AS avghlcomppreon,
    NULL::double precision AS avghlgvsopensysflow,
    NULL::double precision AS avghlgvsopensysret,
    NULL::double precision AS avghlcompopen,
    NULL::double precision AS calcinternhd,
    NULL::double precision AS expendhwpart,
    NULL::double precision AS avghlcond,
    NULL::double precision AS avghlclosesys,
    NULL::double precision AS avghlopensysflow,
    NULL::double precision AS avghlopensysret,
    NULL::double precision AS avghlgvsopenflow,
    NULL::double precision AS avghlgvsopenret,
    NULL::double precision AS avghlgvscloseparall,
    NULL::double precision AS avghlgvsclosemix,
    NULL::double precision AS avghlgvscloseconseq,
    NULL::double precision AS avghlgvsclosepreon,
    NULL::integer AS wemeteringdeviceid,
    NULL::text AS schemenum,
    node_plain.id AS id2,
    'US' AS type_txt,
    0 AS removed
FROM net.node_plain node_plain
WHERE node_plain.removed_at IS NULL
) n
LEFT JOIN (
    SELECT c.fileid, max(c.id) AS cid FROM calc.calculation c GROUP BY c.fileid
) lastcalc ON lastcalc.fileid = n.fileid
LEFT JOIN calc.us_out usp ON usp.nodeid = n.id AND usp.externalsign = 1
                           AND usp.calculationid = lastcalc.cid
LEFT JOIN calc.us_out uso ON uso.nodeid = n.id AND uso.externalsign = 2
                           AND uso.calculationid = lastcalc.cid
LEFT JOIN calc.pt_out  ON pt_out.nodeid = n.id AND pt_out.calculationid = lastcalc.cid
LEFT JOIN calc.dr_out  ON dr_out.nodeid = n.id AND dr_out.calculationid = lastcalc.cid
WHERE n.removed = 0
