-- СГЕНЕРИРОВАНО tools/gen_compat.py
--
-- Слой совместимости: net.v_nodes и net.v_linesobj повторяют форму
-- прежних public.nodes и public.linesobj, но читают из схемы net.
--
-- Создаются РЯДОМ с оригиналом, ничего не переименовывая: это позволяет
-- построчно сверить их с public до какого-либо переключения
-- (tools/check_compat.py). Переключение — отдельный шаг.
--
-- Колонки, которых в net больше нет, восстанавливаются:
--   x, y      — из геометрии (сантиметры, ось Y инвертирована)
--   shape     — это и есть geom
--   coords    — вычисляемая колонка coords_legacy
--   removed   — всегда 0: удалённые в net помечены removed_at
--               и в представление не попадают

CREATE OR REPLACE VIEW net.v_nodes AS
SELECT
    connect_node.id,
    connect_node.internalnodeid,
    connect_node.externalcodeid,
    connect_node.externalnodename,
    connect_node.externalsignid,
    connect_node.addressid,
    connect_node.geomarktoptube,
    connect_node.geomarknodearea,
    connect_node.calcpressflow,
    connect_node.calcpressret,
    connect_node.picdate,
    connect_node.lastrepairdate,
    connect_node.displaysign,
    connect_node.archivechangedate,
    connect_node.operatorid,
    connect_node.nodename,
    connect_node.scheme,
    connect_node.memo,
    connect_node.gpscoords,
    connect_node.belonghn,
    connect_node.passport,
    connect_node.inventnumber,
    connect_node.pipelinesign,
    connect_node.nodetypeid,
    connect_node.isbusy,
    connect_node.isloaded,
    connect_node.belongmagistralsite,
    connect_node.belongdistsite,
    connect_node.organizationid,
    connect_node.magistralsite,
    connect_node.distsite,
    connect_node.registnumber,
    ST_X(connect_node.geom) * 100.0 AS x,
    -ST_Y(connect_node.geom) * 100.0 AS y,
    connect_node.fragment_id AS fileid,
    CASE WHEN connect_node.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    connect_node.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    0 AS id_old
FROM net.connect_node connect_node
UNION ALL
SELECT
    consumer_general.id,
    consumer_general.internalnodeid,
    consumer_general.externalcodeid,
    consumer_general.externalnodename,
    consumer_general.externalsignid,
    consumer_general.addressid,
    consumer_general.geomarktoptube,
    consumer_general.geomarknodearea,
    consumer_general.calcpressflow,
    consumer_general.calcpressret,
    consumer_general.picdate,
    consumer_general.lastrepairdate,
    consumer_general.displaysign,
    consumer_general.archivechangedate,
    consumer_general.operatorid,
    consumer_general.nodename,
    consumer_general.scheme,
    consumer_general.memo,
    consumer_general.gpscoords,
    consumer_general.belonghn,
    consumer_general.passport,
    consumer_general.inventnumber,
    consumer_general.pipelinesign,
    consumer_general.nodetypeid,
    consumer_general.isbusy,
    consumer_general.isloaded,
    consumer_general.belongmagistralsite,
    consumer_general.belongdistsite,
    consumer_general.organizationid,
    consumer_general.magistralsite,
    consumer_general.distsite,
    consumer_general.registnumber,
    ST_X(consumer_general.geom) * 100.0 AS x,
    -ST_Y(consumer_general.geom) * 100.0 AS y,
    consumer_general.fragment_id AS fileid,
    CASE WHEN consumer_general.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    consumer_general.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    0 AS id_old
FROM net.consumer_general consumer_general
UNION ALL
SELECT
    heat_chamber.id,
    heat_chamber.internalnodeid,
    heat_chamber.externalcodeid,
    heat_chamber.externalnodename,
    heat_chamber.externalsignid,
    heat_chamber.addressid,
    heat_chamber.geomarktoptube,
    heat_chamber.geomarknodearea,
    heat_chamber.calcpressflow,
    heat_chamber.calcpressret,
    heat_chamber.picdate,
    heat_chamber.lastrepairdate,
    heat_chamber.displaysign,
    heat_chamber.archivechangedate,
    heat_chamber.operatorid,
    heat_chamber.nodename,
    heat_chamber.scheme,
    heat_chamber.memo,
    heat_chamber.gpscoords,
    heat_chamber.belonghn,
    heat_chamber.passport,
    heat_chamber.inventnumber,
    heat_chamber.pipelinesign,
    heat_chamber.nodetypeid,
    heat_chamber.isbusy,
    heat_chamber.isloaded,
    heat_chamber.belongmagistralsite,
    heat_chamber.belongdistsite,
    heat_chamber.organizationid,
    heat_chamber.magistralsite,
    heat_chamber.distsite,
    heat_chamber.registnumber,
    ST_X(heat_chamber.geom) * 100.0 AS x,
    -ST_Y(heat_chamber.geom) * 100.0 AS y,
    heat_chamber.fragment_id AS fileid,
    CASE WHEN heat_chamber.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    heat_chamber.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    0 AS id_old
FROM net.heat_chamber heat_chamber
UNION ALL
SELECT
    heat_source.id,
    heat_source.internalnodeid,
    heat_source.externalcodeid,
    heat_source.externalnodename,
    heat_source.externalsignid,
    heat_source.addressid,
    heat_source.geomarktoptube,
    heat_source.geomarknodearea,
    heat_source.calcpressflow,
    heat_source.calcpressret,
    heat_source.picdate,
    heat_source.lastrepairdate,
    heat_source.displaysign,
    heat_source.archivechangedate,
    heat_source.operatorid,
    heat_source.nodename,
    heat_source.scheme,
    heat_source.memo,
    heat_source.gpscoords,
    heat_source.belonghn,
    heat_source.passport,
    heat_source.inventnumber,
    heat_source.pipelinesign,
    heat_source.nodetypeid,
    heat_source.isbusy,
    heat_source.isloaded,
    heat_source.belongmagistralsite,
    heat_source.belongdistsite,
    heat_source.organizationid,
    heat_source.magistralsite,
    heat_source.distsite,
    heat_source.registnumber,
    ST_X(heat_source.geom) * 100.0 AS x,
    -ST_Y(heat_source.geom) * 100.0 AS y,
    heat_source.fragment_id AS fileid,
    CASE WHEN heat_source.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    heat_source.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    0 AS id_old
FROM net.heat_source heat_source
UNION ALL
SELECT
    pump_station.id,
    pump_station.internalnodeid,
    pump_station.externalcodeid,
    pump_station.externalnodename,
    pump_station.externalsignid,
    pump_station.addressid,
    pump_station.geomarktoptube,
    pump_station.geomarknodearea,
    pump_station.calcpressflow,
    pump_station.calcpressret,
    pump_station.picdate,
    pump_station.lastrepairdate,
    pump_station.displaysign,
    pump_station.archivechangedate,
    pump_station.operatorid,
    pump_station.nodename,
    pump_station.scheme,
    pump_station.memo,
    pump_station.gpscoords,
    pump_station.belonghn,
    pump_station.passport,
    pump_station.inventnumber,
    pump_station.pipelinesign,
    pump_station.nodetypeid,
    pump_station.isbusy,
    pump_station.isloaded,
    pump_station.belongmagistralsite,
    pump_station.belongdistsite,
    pump_station.organizationid,
    pump_station.magistralsite,
    pump_station.distsite,
    pump_station.registnumber,
    ST_X(pump_station.geom) * 100.0 AS x,
    -ST_Y(pump_station.geom) * 100.0 AS y,
    pump_station.fragment_id AS fileid,
    CASE WHEN pump_station.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    pump_station.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    0 AS id_old
FROM net.pump_station pump_station
UNION ALL
SELECT
    consumer_real.id,
    consumer_real.internalnodeid,
    consumer_real.externalcodeid,
    consumer_real.externalnodename,
    consumer_real.externalsignid,
    consumer_real.addressid,
    consumer_real.geomarktoptube,
    consumer_real.geomarknodearea,
    consumer_real.calcpressflow,
    consumer_real.calcpressret,
    consumer_real.picdate,
    consumer_real.lastrepairdate,
    consumer_real.displaysign,
    consumer_real.archivechangedate,
    consumer_real.operatorid,
    consumer_real.nodename,
    consumer_real.scheme,
    consumer_real.memo,
    consumer_real.gpscoords,
    consumer_real.belonghn,
    consumer_real.passport,
    consumer_real.inventnumber,
    consumer_real.pipelinesign,
    consumer_real.nodetypeid,
    consumer_real.isbusy,
    consumer_real.isloaded,
    consumer_real.belongmagistralsite,
    consumer_real.belongdistsite,
    consumer_real.organizationid,
    consumer_real.magistralsite,
    consumer_real.distsite,
    consumer_real.registnumber,
    ST_X(consumer_real.geom) * 100.0 AS x,
    -ST_Y(consumer_real.geom) * 100.0 AS y,
    consumer_real.fragment_id AS fileid,
    CASE WHEN consumer_real.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    consumer_real.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    0 AS id_old
FROM net.consumer_real consumer_real
UNION ALL
SELECT
    refill_node.id,
    refill_node.internalnodeid,
    refill_node.externalcodeid,
    refill_node.externalnodename,
    refill_node.externalsignid,
    refill_node.addressid,
    refill_node.geomarktoptube,
    refill_node.geomarknodearea,
    refill_node.calcpressflow,
    refill_node.calcpressret,
    refill_node.picdate,
    refill_node.lastrepairdate,
    refill_node.displaysign,
    refill_node.archivechangedate,
    refill_node.operatorid,
    refill_node.nodename,
    refill_node.scheme,
    refill_node.memo,
    refill_node.gpscoords,
    refill_node.belonghn,
    refill_node.passport,
    refill_node.inventnumber,
    refill_node.pipelinesign,
    refill_node.nodetypeid,
    refill_node.isbusy,
    refill_node.isloaded,
    refill_node.belongmagistralsite,
    refill_node.belongdistsite,
    refill_node.organizationid,
    refill_node.magistralsite,
    refill_node.distsite,
    refill_node.registnumber,
    ST_X(refill_node.geom) * 100.0 AS x,
    -ST_Y(refill_node.geom) * 100.0 AS y,
    refill_node.fragment_id AS fileid,
    CASE WHEN refill_node.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    refill_node.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    0 AS id_old
FROM net.refill_node refill_node
UNION ALL
SELECT
    valve_3way.id,
    valve_3way.internalnodeid,
    valve_3way.externalcodeid,
    valve_3way.externalnodename,
    valve_3way.externalsignid,
    valve_3way.addressid,
    valve_3way.geomarktoptube,
    valve_3way.geomarknodearea,
    valve_3way.calcpressflow,
    valve_3way.calcpressret,
    valve_3way.picdate,
    valve_3way.lastrepairdate,
    valve_3way.displaysign,
    valve_3way.archivechangedate,
    valve_3way.operatorid,
    valve_3way.nodename,
    valve_3way.scheme,
    valve_3way.memo,
    valve_3way.gpscoords,
    valve_3way.belonghn,
    valve_3way.passport,
    valve_3way.inventnumber,
    valve_3way.pipelinesign,
    valve_3way.nodetypeid,
    valve_3way.isbusy,
    valve_3way.isloaded,
    valve_3way.belongmagistralsite,
    valve_3way.belongdistsite,
    valve_3way.organizationid,
    valve_3way.magistralsite,
    valve_3way.distsite,
    valve_3way.registnumber,
    ST_X(valve_3way.geom) * 100.0 AS x,
    -ST_Y(valve_3way.geom) * 100.0 AS y,
    valve_3way.fragment_id AS fileid,
    CASE WHEN valve_3way.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    valve_3way.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    0 AS id_old
FROM net.valve_3way valve_3way
UNION ALL
SELECT
    node_plain.id,
    node_plain.internalnodeid,
    node_plain.externalcodeid,
    node_plain.externalnodename,
    node_plain.externalsignid,
    node_plain.addressid,
    node_plain.geomarktoptube,
    node_plain.geomarknodearea,
    node_plain.calcpressflow,
    node_plain.calcpressret,
    node_plain.picdate,
    node_plain.lastrepairdate,
    node_plain.displaysign,
    node_plain.archivechangedate,
    node_plain.operatorid,
    node_plain.nodename,
    node_plain.scheme,
    node_plain.memo,
    node_plain.gpscoords,
    node_plain.belonghn,
    node_plain.passport,
    node_plain.inventnumber,
    node_plain.pipelinesign,
    node_plain.nodetypeid,
    node_plain.isbusy,
    node_plain.isloaded,
    node_plain.belongmagistralsite,
    node_plain.belongdistsite,
    node_plain.organizationid,
    node_plain.magistralsite,
    node_plain.distsite,
    node_plain.registnumber,
    ST_X(node_plain.geom) * 100.0 AS x,
    -ST_Y(node_plain.geom) * 100.0 AS y,
    node_plain.fragment_id AS fileid,
    CASE WHEN node_plain.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    node_plain.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    0 AS id_old
FROM net.node_plain node_plain;

CREATE OR REPLACE VIEW net.v_linesobj AS
SELECT
    air_heater.id,
    air_heater.node_from_src AS nodeid1,
    air_heater.node_to_src AS nodeid2,
    air_heater.externalsignlineid,
    air_heater.location,
    air_heater.hydrores,
    air_heater.organizationid,
    air_heater.registnum,
    air_heater.firstpicdate,
    air_heater.lastmaintdate,
    air_heater.displaysign,
    air_heater.archivechangedate,
    air_heater.operatorid,
    air_heater.coords_legacy AS coords,
    air_heater.typ,
    CASE WHEN air_heater.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    air_heater.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    air_heater.fileid_src AS fileid,
    air_heater.internalnodeid,
    0 AS id_old
FROM net.air_heater air_heater
UNION ALL
SELECT
    damper.id,
    damper.node_from_src AS nodeid1,
    damper.node_to_src AS nodeid2,
    damper.externalsignlineid,
    damper.location,
    damper.hydrores,
    damper.organizationid,
    damper.registnum,
    damper.firstpicdate,
    damper.lastmaintdate,
    damper.displaysign,
    damper.archivechangedate,
    damper.operatorid,
    damper.coords_legacy AS coords,
    damper.typ,
    CASE WHEN damper.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    damper.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    damper.fileid_src AS fileid,
    damper.internalnodeid,
    0 AS id_old
FROM net.damper damper
UNION ALL
SELECT
    diaphragm.id,
    diaphragm.node_from_src AS nodeid1,
    diaphragm.node_to_src AS nodeid2,
    diaphragm.externalsignlineid,
    diaphragm.location,
    diaphragm.hydrores,
    diaphragm.organizationid,
    diaphragm.registnum,
    diaphragm.firstpicdate,
    diaphragm.lastmaintdate,
    diaphragm.displaysign,
    diaphragm.archivechangedate,
    diaphragm.operatorid,
    diaphragm.coords_legacy AS coords,
    diaphragm.typ,
    CASE WHEN diaphragm.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    diaphragm.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    diaphragm.fileid_src AS fileid,
    diaphragm.internalnodeid,
    0 AS id_old
FROM net.diaphragm diaphragm
UNION ALL
SELECT
    elevator.id,
    elevator.node_from_src AS nodeid1,
    elevator.node_to_src AS nodeid2,
    elevator.externalsignlineid,
    elevator.location,
    elevator.hydrores,
    elevator.organizationid,
    elevator.registnum,
    elevator.firstpicdate,
    elevator.lastmaintdate,
    elevator.displaysign,
    elevator.archivechangedate,
    elevator.operatorid,
    elevator.coords_legacy AS coords,
    elevator.typ,
    CASE WHEN elevator.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    elevator.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    elevator.fileid_src AS fileid,
    elevator.internalnodeid,
    0 AS id_old
FROM net.elevator elevator
UNION ALL
SELECT
    heat_exchanger.id,
    heat_exchanger.node_from_src AS nodeid1,
    heat_exchanger.node_to_src AS nodeid2,
    heat_exchanger.externalsignlineid,
    heat_exchanger.location,
    heat_exchanger.hydrores,
    heat_exchanger.organizationid,
    heat_exchanger.registnum,
    heat_exchanger.firstpicdate,
    heat_exchanger.lastmaintdate,
    heat_exchanger.displaysign,
    heat_exchanger.archivechangedate,
    heat_exchanger.operatorid,
    heat_exchanger.coords_legacy AS coords,
    heat_exchanger.typ,
    CASE WHEN heat_exchanger.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    heat_exchanger.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    heat_exchanger.fileid_src AS fileid,
    heat_exchanger.internalnodeid,
    0 AS id_old
FROM net.heat_exchanger heat_exchanger
UNION ALL
SELECT
    pipe_section.id,
    pipe_section.node_from_src AS nodeid1,
    pipe_section.node_to_src AS nodeid2,
    pipe_section.externalsignlineid,
    pipe_section.location,
    pipe_section.hydrores,
    pipe_section.organizationid,
    pipe_section.registnum,
    pipe_section.firstpicdate,
    pipe_section.lastmaintdate,
    pipe_section.displaysign,
    pipe_section.archivechangedate,
    pipe_section.operatorid,
    pipe_section.coords_legacy AS coords,
    pipe_section.typ,
    CASE WHEN pipe_section.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    pipe_section.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    pipe_section.fileid_src AS fileid,
    pipe_section.internalnodeid,
    0 AS id_old
FROM net.pipe_section pipe_section
UNION ALL
SELECT
    local_resistance.id,
    local_resistance.node_from_src AS nodeid1,
    local_resistance.node_to_src AS nodeid2,
    local_resistance.externalsignlineid,
    local_resistance.location,
    local_resistance.hydrores,
    local_resistance.organizationid,
    local_resistance.registnum,
    local_resistance.firstpicdate,
    local_resistance.lastmaintdate,
    local_resistance.displaysign,
    local_resistance.archivechangedate,
    local_resistance.operatorid,
    local_resistance.coords_legacy AS coords,
    local_resistance.typ,
    CASE WHEN local_resistance.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    local_resistance.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    local_resistance.fileid_src AS fileid,
    local_resistance.internalnodeid,
    0 AS id_old
FROM net.local_resistance local_resistance
UNION ALL
SELECT
    regulator_press.id,
    regulator_press.node_from_src AS nodeid1,
    regulator_press.node_to_src AS nodeid2,
    regulator_press.externalsignlineid,
    regulator_press.location,
    regulator_press.hydrores,
    regulator_press.organizationid,
    regulator_press.registnum,
    regulator_press.firstpicdate,
    regulator_press.lastmaintdate,
    regulator_press.displaysign,
    regulator_press.archivechangedate,
    regulator_press.operatorid,
    regulator_press.coords_legacy AS coords,
    regulator_press.typ,
    CASE WHEN regulator_press.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    regulator_press.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    regulator_press.fileid_src AS fileid,
    regulator_press.internalnodeid,
    0 AS id_old
FROM net.regulator_press regulator_press
UNION ALL
SELECT
    pump.id,
    pump.node_from_src AS nodeid1,
    pump.node_to_src AS nodeid2,
    pump.externalsignlineid,
    pump.location,
    pump.hydrores,
    pump.organizationid,
    pump.registnum,
    pump.firstpicdate,
    pump.lastmaintdate,
    pump.displaysign,
    pump.archivechangedate,
    pump.operatorid,
    pump.coords_legacy AS coords,
    pump.typ,
    CASE WHEN pump.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    pump.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    pump.fileid_src AS fileid,
    pump.internalnodeid,
    0 AS id_old
FROM net.pump pump
UNION ALL
SELECT
    radiator.id,
    radiator.node_from_src AS nodeid1,
    radiator.node_to_src AS nodeid2,
    radiator.externalsignlineid,
    radiator.location,
    radiator.hydrores,
    radiator.organizationid,
    radiator.registnum,
    radiator.firstpicdate,
    radiator.lastmaintdate,
    radiator.displaysign,
    radiator.archivechangedate,
    radiator.operatorid,
    radiator.coords_legacy AS coords,
    radiator.typ,
    CASE WHEN radiator.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    radiator.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    radiator.fileid_src AS fileid,
    radiator.internalnodeid,
    0 AS id_old
FROM net.radiator radiator
UNION ALL
SELECT
    line_plain.id,
    line_plain.node_from_src AS nodeid1,
    line_plain.node_to_src AS nodeid2,
    line_plain.externalsignlineid,
    line_plain.location,
    line_plain.hydrores,
    line_plain.organizationid,
    line_plain.registnum,
    line_plain.firstpicdate,
    line_plain.lastmaintdate,
    line_plain.displaysign,
    line_plain.archivechangedate,
    line_plain.operatorid,
    line_plain.coords_legacy AS coords,
    line_plain.typ,
    CASE WHEN line_plain.removed_at IS NULL THEN 0 ELSE 1 END AS removed,
    NULL::int AS idremoved,
    line_plain.geom AS shape,
    NULL::text AS globalid,
    NULL::text AS gistable,
    NULL::boolean AS sync,
    NULL::boolean AS gis,
    false AS sync_tgid,
    line_plain.fileid_src AS fileid,
    line_plain.internalnodeid,
    0 AS id_old
FROM net.line_plain line_plain;
