-- Слой совместимости для СТАРОГО приложения gid8 — в отдельной схеме.
--
-- gid8 обращается к nodes в 219 файлах, к linesobj в 112, к fragments
-- в 109 — всего 362 имени старой модели в 403 файлах. Переписать это
-- на net значит переписать приложение; работа на месяцы.
--
-- Поэтому представления возвращаются, но НЕ в public: схема compat
-- не входит в search_path базы, и продуктовый контур — Qt-клиент,
-- движок расчёта, QGIS — её не видит. Видит только gid8, который
-- задаёт свой порядок поиска при подключении (gid8/db/db.cpp).
--
-- Так выполняются оба требования: gid8 работает полностью, а «ничего
-- старого» остаётся верным для всех, кто работает с продуктовой
-- моделью. Когда gid8 выведут из эксплуатации, схема удаляется целиком
-- и больше ничего не задевает.
--
-- Определения — снимок, снятый перед удалением слоя в шаге 47
-- (sql/161_compat_restore.sql). Триггеров INSTEAD OF на них нет:
-- запись обрабатывают триггеры на net.v_*, а это простые обёртки,
-- которые PostgreSQL пробрасывает сам.
--
-- Откат: DROP SCHEMA compat CASCADE;

BEGIN;

CREATE SCHEMA IF NOT EXISTS compat;

COMMENT ON SCHEMA compat IS
    'Представления старой модели ТГИД для приложения gid8. В search_path '
    'базы не входит: продуктовый контур работает с net/ref/calc напрямую.';


CREATE OR REPLACE VIEW compat.airheaters AS
 SELECT id,
    lineid,
    faninstall,
    scheme,
    airheaterscount,
    rowscount,
    storescount,
    airheatertype,
    contamincoeff,
    presscoeff,
    location
   FROM v_airheaters;

CREATE OR REPLACE VIEW compat.connectnodes AS
 SELECT id,
    nodeid,
    connectid
   FROM v_connectnodes;

CREATE OR REPLACE VIEW compat.dampers AS
 SELECT id,
    lineid,
    dispatcherswitch,
    diametercondit,
    partdempopen,
    name,
    standarddamplink,
    turncount,
    gatecontrol,
    clue,
    thrustcollar,
    relatleakage,
    opc,
    damperarmaturestateid
   FROM v_dampers;

CREATE OR REPLACE VIEW compat.diaphragms AS
 SELECT id,
    lineid,
    throtdiaphloc,
    diameterinternal,
    consinstdiaphcount,
    entrymark,
    stateid
   FROM v_diaphragms;

CREATE OR REPLACE VIEW compat.elevators AS
 SELECT id,
    lineid,
    elevatortype,
    elevatornuminst,
    diameternozzle,
    entrymark,
    diameterchamber,
    length,
    diameterinletflange,
    diameteroutletflange,
    diametersuctionpipe,
    material,
    stateid
   FROM v_elevators;

CREATE OR REPLACE VIEW compat.generalizedconsumers AS
 SELECT id,
    nodeid,
    quarter,
    maxbuildingheight,
    accumcoeff,
    hydromodesignid,
    specexpendid,
    calctemperatureid,
    gvsloadgraphid,
    varcoeffid,
    normhlosflow,
    normhlosret,
    calchldep,
    calcinternhddep,
    adjcalchldep,
    adjcalchddep,
    perspcalchldep,
    perspcalcinternhddep,
    calctempdep,
    connectionschemeid,
    mixfactcoeffdep,
    calchlindep,
    calcinternhdindep,
    adjcalchlindep,
    adjcalcinternhdindep,
    perspcalchlindep,
    perspcalcinternhdindep,
    calctempindep,
    mixfactcoeffindep,
    calchlventil,
    adjcalchlventil,
    perspcalchlventil,
    calchlcond,
    adjcalchlcond,
    perspcalchlcond,
    calchlclosesys,
    calchlopensysflow,
    calchlopensysret,
    adjcalchlclosesys,
    adjcalchlopensysflow,
    adjcalchlopensysret,
    perspcalchlclosesys,
    perspcalchlopensysflow,
    perspcalchlopensysret,
    expendhwpart,
    calctempha,
    calchlparall,
    internhdparall,
    adjcalchlparall,
    adjinternhdparall,
    perspcalchlparall,
    perspinternhdparall,
    schemeparallid,
    calchlgvsparall,
    adjcalchlgvsparall,
    perspcalchlgvsparall,
    hourirregcoeffparall,
    avghlcompparall,
    temprecircpipeparall,
    calctemphrparall,
    calctemphwdoparall,
    amrdepparall,
    calchlmix,
    internhdmix,
    adjcalchlmix,
    adjinternhdmix,
    perspcalchlmix,
    perspinternhdmix,
    schememixid,
    calchlgvsmix,
    adjcalchlgvsmix,
    perspcalchlgvsmix,
    hourirregcoeffmix,
    avghlcompmix,
    temprecircpipemix,
    calctemphrmix,
    calctemphwdomix,
    amrdepmix,
    calchlconseq,
    internhdconseq,
    adjcalchlconseq,
    adjinternhdconseq,
    perspcalchlconseq,
    perspinternhdconseq,
    schemeconseqid,
    calchlgvsconseq,
    adjcalchlgvsconseq,
    perspcalchlgvsconseq,
    hourirregcoeffconseq,
    avghlcompconseq,
    temprecircpipeconseq,
    calctemphrconseq,
    calctemphwdoconseq,
    amrdepconseq,
    calchlpreon,
    internhdpreon,
    adjcalchlpreon,
    adjinternhdpreon,
    perspcalchlpreon,
    perspinternhdpreon,
    schemepreonid,
    calchlgvspreon,
    adjcalchlgvspreon,
    perspcalchlgvspreon,
    hourirregcoeffpreon,
    avghlcomppreon,
    temprecircpipepreon,
    calctemphrpreon,
    calctemphwdopreon,
    amrdeppreon,
    avghlgvsopensysflow,
    avghlgvsopensysret,
    adjavghlgvsopensysflow,
    adjavghlgvsopensysret,
    perspavghlgvsopensysflow,
    perspavghlgvsopensysret,
    hourirregcoeffopen,
    avghlcompopen,
    temprecircpipeopen,
    calctemphwdoopen,
    pdvalveinstalllocid,
    setpdonregulator,
    setleakageflow,
    setleakageret,
    wemeteringdeviceid,
    volwaterhs,
    volwatervs,
    minthrustds,
    hydroresclosesys,
    hydroresclosesyssummer,
    closesyscalcsignid,
    hydroreswdoflow,
    calcsignopensysflowid,
    hydroreswdoret,
    calcsignreswdoretid,
    calcsignsetloadclosesys,
    calcsignsetloadopensysflow,
    calcsignsetloadopensysret,
    hydrothrustin,
    hydrothrustout,
    calcexpenddep,
    calcexpendindep,
    calcexpendventil,
    calcexpendcond,
    calcexpendhwflow,
    calcexpendhwret,
    calcexpendrecircopen,
    calcexpendhwparall,
    calcexpendhwmix,
    calcexpendhwconseq,
    calcexpendhwpreon,
    calcthrustinwsd,
    consumerstateid,
    name
   FROM v_generalizedconsumers;

CREATE OR REPLACE VIEW compat.heatchambers AS
 SELECT id,
    nodeid,
    name,
    slotscount,
    slotsweight,
    internalheight,
    internalwidth,
    internallength,
    wallmaterial,
    stairscount,
    stoparmaturecount,
    ballvalvescount,
    airventscount
   FROM v_heatchambers;

CREATE OR REPLACE VIEW compat.heatexchangers AS
 SELECT id,
    lineid,
    heatexchtype,
    heatexchcode,
    location,
    stateid
   FROM v_heatexchangers;

CREATE OR REPLACE VIEW compat.heatpipesections AS
 SELECT id,
    lineid,
    pipesectionid,
    pipesectstateidflow,
    pipesectstateidret,
    standardid,
    standardtubelink,
    tubescount,
    diameterinternal,
    diametercondit,
    diameterexternal,
    wallthickness,
    pipesectlength,
    tuberoughness,
    locallosesshare,
    localressum,
    varcoeffidflow,
    varcoeffidret,
    calcheatlossignid,
    tubingtypeid,
    piperemonttypeid,
    channelid,
    constrchanwidth,
    constrchanheight,
    heattestscoeff,
    signnumwork,
    isolmaterialid,
    isolthickness,
    isolmaterialhccoeff,
    pipelinelayingdepth,
    isolhtcoeffabove,
    isolhtcoeffunder,
    airgroundhtcoeffunder,
    groundhccoeff,
    pipelineaxesdist,
    damagenum,
    lasttransdate,
    lastisoldate,
    repairdatecapital,
    picdatecapital,
    repairdatemaint,
    picdatemaint,
    repairdateplantp,
    firstpicdatehp,
    lastmaintdatehp,
    sectexploitperiod,
    buildingconstrstateid,
    specdamagecoeff,
    specdamagecoeff2,
    powcabinstcount10,
    powcabinstcount5,
    powcabinstcount3,
    powcabinstcount1,
    powcabinstcount0,
    powcabinterscount,
    gasecpcount10,
    gasecpcount5,
    gasecpcount3,
    gasecpcount1,
    gasecpcount0,
    gasecpinterscount,
    eltranspcount10,
    eltranspcount5,
    eltranspcount3,
    eltranspcount1,
    eltranspcount0,
    eltranspinterscount,
    potentialdifflevelid,
    corrosiondegoutid,
    corrosiondeginid,
    floodintensitygwid,
    floodintensityfwid,
    floodintensitytwid,
    floodintensitybwid,
    jointstightnessinfr,
    chanconstrfract,
    projsoldeviation,
    constrbearreduce,
    fixedsuppdestr,
    sectwaterdumpid,
    breakcomplexityid,
    breakconsumvolid,
    erwdifficultyid,
    tubingpedestrianid,
    tubingwayid,
    populdamageid,
    infrastrdamageid,
    hydratestsdate,
    sectexpend,
    sectthrustloses,
    heattestsdate,
    temperoutair,
    temperground,
    expenddwflow,
    expenddwret,
    tempercoolflow,
    tempercoolret,
    temperdwflow,
    temperdwret,
    opc,
    tubecharactid,
    tubetypeid,
    tubematerial,
    tempermax,
    factorymanufid,
    externmaterialid,
    isolationtypeid,
    externcoverthick,
    anticorrmaterialid,
    magistralsite,
    distsite,
    exploitreg,
    net,
    magistral,
    exploitsite,
    nettype,
    crimpingquesite,
    h,
    deltah,
    deltaq,
    q,
    primechanie,
    name,
    inventnumber,
    objecttypeid,
    sreda,
    press,
    temperature,
    spoksluzhbirash,
    ressurs,
    pusk,
    organizationid,
    elektrich,
    transportelekricht,
    ponezial,
    vodootved,
    slozhokluzh,
    otkluzhgkal,
    avariivipoln,
    pesehod,
    zhddorogi,
    ludiproklad,
    uzherbludi,
    uzherbsity,
    vnesniivid,
    sostoborudovania,
    vnesnkorrozia,
    vnunrenkorrozia,
    sostkonstrukz,
    kategorii,
    mestn
   FROM v_heatpipesections;

CREATE OR REPLACE VIEW compat.heatsources AS
 SELECT id,
    nodeid,
    sourcename,
    name,
    stateid,
    hsourcetypeid,
    hsourceid,
    hsourcepower,
    hsourcepowerinst,
    hseasonbegindate,
    hseasonenddate,
    hsourcecode,
    temperdwflowsummer,
    temperdwretsummer,
    specvolhs,
    specvolvent,
    expenddwnorm1,
    expenddwnorm2,
    expenddwnorm3,
    expenddwnorm4,
    expenddwnorm5,
    managerphone,
    controllerphone,
    powerset,
    poweravailable,
    heighttubemark,
    heightareamark,
    repairworks,
    t1_summer,
    t2_summer,
    name_tg,
    heatloscalcyear,
    graphtypeid,
    tn_1,
    tn_5,
    tvn_r,
    t1_r,
    t2_r,
    t3_r,
    q_r,
    t1_2r,
    t1_4r,
    tvb_tr,
    uf,
    t2_2r,
    q_gv,
    tg_r,
    tx_r,
    t2_gv,
    pr,
    g1,
    g2,
    t_gv1,
    deployedtempgraphid,
    v,
    date_on,
    name_exe,
    name_manager,
    dt2_co,
    t2pod_parl,
    dt2v_sm_noavm,
    dt2v_sm_avm,
    t1pod_sm,
    t1pod_posll,
    dt2v_posl,
    length_1,
    length_2,
    length_3,
    length_4,
    length_5,
    length_6,
    length_7,
    length_8,
    length_9,
    length_10,
    length_11,
    length_12,
    t_1,
    t_2,
    t_3,
    t_4,
    t_5,
    t_6,
    t_7,
    t_8,
    t_9,
    t_10,
    t_11,
    t_12,
    t1_1,
    t1_2,
    t1_3,
    t1_4,
    t1_5,
    t1_6,
    t1_7,
    t1_8,
    t1_9,
    t1_10,
    t1_11,
    t1_12,
    t2_1,
    t2_2,
    t2_3,
    t2_4,
    t2_5,
    t2_6,
    t2_7,
    t2_8,
    t2_9,
    t2_10,
    t2_11,
    t2_12,
    length_1_fakt,
    length_2_fakt,
    length_3_fakt,
    length_4_fakt,
    length_5_fakt,
    length_6_fakt,
    length_7_fakt,
    length_8_fakt,
    length_9_fakt,
    length_10_fakt,
    length_11_fakt,
    length_12_fakt,
    t_1_fakt,
    t_2_fakt,
    t_3_fakt,
    t_4_fakt,
    t_5_fakt,
    t_6_fakt,
    t_7_fakt,
    t_8_fakt,
    t_9_fakt,
    t_10_fakt,
    t_11_fakt,
    t_12_fakt,
    t1_1_fakt,
    t1_2_fakt,
    t1_3_fakt,
    t1_4_fakt,
    t1_5_fakt,
    t1_6_fakt,
    t1_7_fakt,
    t1_8_fakt,
    t1_9_fakt,
    t1_10_fakt,
    t1_11_fakt,
    t1_12_fakt,
    t2_1_fakt,
    t2_2_fakt,
    t2_3_fakt,
    t2_4_fakt,
    t2_5_fakt,
    t2_6_fakt,
    t2_7_fakt,
    t2_8_fakt,
    t2_9_fakt,
    t2_10_fakt,
    t2_11_fakt,
    t2_12_fakt,
    gpod_1_fakt,
    gpod_2_fakt,
    gpod_3_fakt,
    gpod_4_fakt,
    gpod_5_fakt,
    gpod_6_fakt,
    gpod_7_fakt,
    gpod_8_fakt,
    gpod_9_fakt,
    gpod_10_fakt,
    gpod_11_fakt,
    gpod_12_fakt,
    ggvs_pribor_1_fakt,
    ggvs_pribor_2_fakt,
    ggvs_pribor_3_fakt,
    ggvs_pribor_4_fakt,
    ggvs_pribor_5_fakt,
    ggvs_pribor_6_fakt,
    ggvs_pribor_7_fakt,
    ggvs_pribor_8_fakt,
    ggvs_pribor_9_fakt,
    ggvs_pribor_10_fakt,
    ggvs_pribor_11_fakt,
    ggvs_pribor_12_fakt,
    gakt_tex_1_fakt,
    gakt_tex_2_fakt,
    gakt_tex_3_fakt,
    gakt_tex_4_fakt,
    gakt_tex_5_fakt,
    gakt_tex_6_fakt,
    gakt_tex_7_fakt,
    gakt_tex_8_fakt,
    gakt_tex_9_fakt,
    gakt_tex_10_fakt,
    gakt_tex_11_fakt,
    gakt_tex_12_fakt,
    gakt_avarija_1_fakt,
    gakt_avarija_2_fakt,
    gakt_avarija_3_fakt,
    gakt_avarija_4_fakt,
    gakt_avarija_5_fakt,
    gakt_avarija_6_fakt,
    gakt_avarija_7_fakt,
    gakt_avarija_8_fakt,
    gakt_avarija_9_fakt,
    gakt_avarija_10_fakt,
    gakt_avarija_11_fakt,
    gakt_avarija_12_fakt,
    id_old
   FROM v_heatsources;

CREATE OR REPLACE VIEW compat.linesobj AS
 SELECT id,
    nodeid1,
    nodeid2,
    externalsignlineid,
    location,
    hydrores,
    organizationid,
    registnum,
    firstpicdate,
    lastmaintdate,
    displaysign,
    archivechangedate,
    operatorid,
    coords,
    typ,
    removed,
    idremoved,
    shape,
    globalid,
    gistable,
    sync,
    gis,
    sync_tgid,
    fileid,
    internalnodeid,
    id_old
   FROM v_linesobj;

CREATE OR REPLACE VIEW compat.localhydroresistances2 AS
 SELECT id,
    lineid,
    name_mest,
    s_mest,
    k_mest,
    sum_mest
   FROM v_localhydroresistances2;

-- Эксплуатационный справочник перенесён в attic после раскладки его
-- значений по объектным таблицам, но старый DockPTS всё ещё показывает и
-- редактирует его отдельным экраном. Простое представление остаётся
-- автоматически обновляемым.
CREATE OR REPLACE VIEW compat.magistrali AS
 SELECT *
 FROM attic.magistrali;

CREATE OR REPLACE VIEW compat.nodes AS
 SELECT id,
    internalnodeid,
    externalcodeid,
    externalnodename,
    externalsignid,
    addressid,
    geomarktoptube,
    geomarknodearea,
    calcpressflow,
    calcpressret,
    picdate,
    lastrepairdate,
    displaysign,
    archivechangedate,
    operatorid,
    nodename,
    scheme,
    memo,
    gpscoords,
    belonghn,
    passport,
    inventnumber,
    pipelinesign,
    nodetypeid,
    isbusy,
    isloaded,
    belongmagistralsite,
    belongdistsite,
    organizationid,
    magistralsite,
    distsite,
    registnumber,
    x,
    y,
    fileid,
    removed,
    idremoved,
    shape,
    globalid,
    gistable,
    sync,
    gis,
    sync_tgid,
    id_old
   FROM v_nodes;

CREATE OR REPLACE VIEW compat.pressregulators AS
 SELECT id,
    lineid,
    nodeid,
    valvehydroresopen,
    valvehydroresclose,
    regvalverelcap,
    relleakage,
    consdrip,
    workattrid,
    deltah,
    regulatorstateid,
    h,
    pipelinesignid
   FROM v_pressregulators;

CREATE OR REPLACE VIEW compat.pumps AS
 SELECT id,
    lineid,
    offreason,
    pumpstationid,
    number,
    thrust,
    standardpumpid,
    parallagregcount,
    drivetypeid,
    rotordiametertypeid,
    standardemid,
    r0,
    r1,
    r2,
    e0,
    e1,
    e2,
    k0,
    k1,
    k2,
    r0_z,
    r1_z,
    r2_z,
    e0_z,
    e1_z,
    e2_z,
    k0_z,
    k1_z,
    k2_z,
    rotorrotspeedset,
    rotordiameterset,
    lastpumpreplacedate,
    lastemreplacedate,
    lastagregreplacedate,
    repaircountpump,
    replacecountagreg,
    repaircountem,
    opc,
    stateid
   FROM v_pumps;

CREATE OR REPLACE VIEW compat.pumpstations AS
 SELECT id,
    nodeid,
    name,
    purpose,
    capacity,
    pumpcountflow,
    pumpcountret,
    state,
    stateid,
    heighttubemark,
    heightareamark
   FROM v_pumpstations;

CREATE OR REPLACE VIEW compat.realconsumers AS
 SELECT id,
    nodeid,
    name,
    consumerstateid,
    automdegid,
    sectconsumercode,
    schemenum,
    buildheight,
    accumcoeff,
    specexpendid,
    calctemperatureid,
    gvsloadgraphid,
    varcoeffid,
    calchldep,
    calchlindep,
    relloadfacade,
    calcinternhd,
    contcalchldep,
    contcalchlindep,
    contrelloadfacade,
    continternhd,
    perspcalchldep,
    perspcalchlindep,
    persprelloadfacade,
    perspinternhd,
    calchlventil,
    expendhwpart,
    contcalchlventil,
    perspcalchlventil,
    avghlcond,
    contavghlcond,
    perspavghlcond,
    avghlclosesys,
    avghlopensysflow,
    avghlopensysret,
    contavghlclosesys,
    contavghlopensysflow,
    contavghlopensysret,
    perspavghlclose,
    perspavghlopenflow,
    contavghlopenret,
    avghlgvsopenflow,
    avghlgvsopenret,
    avghlgvscloseparall,
    avghlgvsclosemix,
    avghlgvscloseconseq,
    avghlgvsclosepreon,
    contavghlgvsopenflow,
    contavghlgvsopenret,
    contavghlgvscloseparall,
    contavghlgvsclosemix,
    contavghlgvscloseconseq,
    contavghlgvsclosepreon,
    perspavghlgvsopenflow,
    perspavghlgvsopenret,
    perspavghlgvscloseparall,
    perspavghlgvsclosemix,
    perspavghlgvscloseconseq,
    perspavghlgvsclosepreon,
    hydromodesignid,
    mixfactcoeff,
    hourirregcoeff,
    circhlosopen,
    temprecircpipe,
    setleakageflow,
    setleakageret,
    wemeteringdeviceid,
    volwaterhs,
    volwatervs,
    hydroresclosesys,
    hydroresclosesyssummer,
    closesyscalcsignid,
    hydroreswdoflow,
    calcsignopensysflowid,
    hydroreswdoret,
    calcsignreswdoretid,
    calcsignsetloadclosesys,
    calcsignsetloadopensysflow,
    calcsignsetloadopensysret,
    hydrothrustin,
    hydrothrustout,
    calcexpenddep,
    calcexpendindep,
    calcexpendventil,
    calcexpendcond,
    calcexpendhwflow,
    calcexpendhwret,
    calcexpendrecircopen,
    calcexpendhwparall,
    calcexpendhwmix,
    calcexpendhwconseq,
    calcexpendhwpreon,
    throtstagesignid,
    diameterthrotdiaph,
    diameterelevnozzle,
    temperchartsignid,
    calcsignres,
    calcsignhl,
    parallheaterscount1,
    parallheaterscount2,
    parallheaterscountindep,
    calcthrustloshs,
    calcthrustlosah,
    calcthrustlosac,
    calcthrustlosflow,
    calcthrustlosflowcirc,
    calcthrustinwdo,
    calcthrustlosheaters1,
    calcthrustlosheaters2,
    pdvalveinstalllocid,
    setpdonregulator,
    calcferdiametersignid,
    calctemphr,
    calctempvs,
    calctemphwdo,
    responsibleid,
    contractnumber,
    stopvalvetypeid,
    meterdevworksign,
    meterdevsafety,
    meterdevstampnum,
    isolationtype,
    buildingtypeid,
    heatsourceptsid,
    heatpointid,
    countusergv,
    countbusinessconsumers,
    area,
    buildingvolume,
    basementvolume,
    builtinvolume,
    reducebuildingvolume,
    countfloors,
    builtyear,
    streetid,
    housenumber,
    note_1,
    note_2,
    note_pts,
    note_regime,
    b23,
    b28,
    b32,
    b20,
    b14,
    b38,
    b35,
    b36,
    zd7,
    zd8,
    zd27,
    zd28,
    zd36,
    zd38,
    zd39,
    zd48,
    zd49,
    zd50,
    elevatornuminst,
    diameternozzle
   FROM v_realconsumers;

CREATE OR REPLACE VIEW compat.refillnodes AS
 SELECT id,
    nodeid,
    externalsignid,
    refillexpend,
    wdo,
    refillloss,
    diameterinternal,
    watervolup,
    watervoldown,
    watervolupset,
    potscount,
    potssumvol,
    potworkingsign,
    chargeexpend,
    dischargeexpend,
    setpressret
   FROM v_refillnodes;

CREATE OR REPLACE VIEW compat.systemradiators AS
 SELECT id,
    lineid,
    name,
    type,
    count,
    totalequivsurface,
    stateid
   FROM v_systemradiators;

CREATE OR REPLACE VIEW compat.threewayvalves AS
 SELECT id,
    nodeid,
    structure,
    state,
    purpose,
    calcmixfactcoeff,
    calcthrustlos,
    expendcharstraight,
    expendcharvert,
    authority,
    calccapdeviation,
    type,
    capacity,
    regulator,
    maxpd,
    diameternomin,
    calcexpendnodemix,
    pumpstationname
   FROM v_threewayvalves;

COMMIT;

SELECT count(*) AS predstavleniy_v_compat
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'compat' AND c.relkind = 'v';
